# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qtaxis.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from qtvcp.widgets.gcode_graphics import GCodeGraphics
from qtvcp.widgets.status_slider import StatusSlider
from qtvcp.widgets.axis_tool_button import AxisToolButton
from qtvcp.widgets.radio_axis_selector import RadioAxisSelector
from qtvcp.widgets.jog_increments import JogIncrements
from qtvcp.widgets.screen_options import ScreenOptions
from qtvcp.widgets.status_label import StatusLabel
from qtvcp.widgets.dro_widget import DROLabel
from qtvcp.widgets.detach_tabs import DetachTabWidget
from qtvcp.widgets.offset_tool_button import OffsetToolButton
from qtvcp.widgets.gcode_editor import GcodeEditor
from qtvcp.widgets.mdi_history import MDIHistory
from qtvcp.widgets.action_button import ActionButton


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(802, 626)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionQuickRef = QAction(MainWindow)
        self.actionQuickRef.setObjectName(u"actionQuickRef")
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionEdit.setCheckable(True)
        self.actionReload = QAction(MainWindow)
        self.actionReload.setObjectName(u"actionReload")
        icon = QIcon()
        icon.addFile(u"../../../axis/images/tool_reload.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReload.setIcon(icon)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionProperties = QAction(MainWindow)
        self.actionProperties.setObjectName(u"actionProperties")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon1 = QIcon()
        icon1.addFile(u"../../../axis/images/close.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionEstop = QAction(MainWindow)
        self.actionEstop.setObjectName(u"actionEstop")
        self.actionEstop.setCheckable(True)
        icon2 = QIcon()
        icon2.addFile(u"../../../axis/images/tool_estop.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionEstop.setIcon(icon2)
        self.actionMachineOn = QAction(MainWindow)
        self.actionMachineOn.setObjectName(u"actionMachineOn")
        self.actionMachineOn.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u"../../../axis/images/tool_power.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMachineOn.setIcon(icon3)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon4 = QIcon()
        icon4.addFile(u"../../../axis/images/tool_open.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon4)
        self.actionRun = QAction(MainWindow)
        self.actionRun.setObjectName(u"actionRun")
        icon5 = QIcon()
        icon5.addFile(u"../../../axis/images/tool_run.gif", QSize(), QIcon.Normal, QIcon.On)
        self.actionRun.setIcon(icon5)
        self.actionStep = QAction(MainWindow)
        self.actionStep.setObjectName(u"actionStep")
        icon6 = QIcon()
        icon6.addFile(u"../../../axis/images/tool_step.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionStep.setIcon(icon6)
        self.actionPause = QAction(MainWindow)
        self.actionPause.setObjectName(u"actionPause")
        self.actionPause.setCheckable(True)
        icon7 = QIcon()
        icon7.addFile(u"../../../axis/images/tool_pause.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPause.setIcon(icon7)
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        icon8 = QIcon()
        icon8.addFile(u"../../../axis/images/tool_stop.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionStop.setIcon(icon8)
        self.actionSkip = QAction(MainWindow)
        self.actionSkip.setObjectName(u"actionSkip")
        self.actionSkip.setCheckable(True)
        icon9 = QIcon()
        icon9.addFile(u"../../../axis/images/tool_blockdelete.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSkip.setIcon(icon9)
        self.actionOptionalStop = QAction(MainWindow)
        self.actionOptionalStop.setObjectName(u"actionOptionalStop")
        self.actionOptionalStop.setCheckable(True)
        icon10 = QIcon()
        icon10.addFile(u"../../../axis/images/tool_optpause.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOptionalStop.setIcon(icon10)
        self.actionZoomIn = QAction(MainWindow)
        self.actionZoomIn.setObjectName(u"actionZoomIn")
        icon11 = QIcon()
        icon11.addFile(u"../../../axis/images/tool_zoomin.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoomIn.setIcon(icon11)
        self.actionZoomOut = QAction(MainWindow)
        self.actionZoomOut.setObjectName(u"actionZoomOut")
        icon12 = QIcon()
        icon12.addFile(u"../../../axis/images/tool_zoomout.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoomOut.setIcon(icon12)
        self.actionTopView = QAction(MainWindow)
        self.actionTopView.setObjectName(u"actionTopView")
        self.actionTopView.setCheckable(True)
        icon13 = QIcon()
        icon13.addFile(u"../../../axis/images/tool_axis_z.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTopView.setIcon(icon13)
        self.actionRotatedView = QAction(MainWindow)
        self.actionRotatedView.setObjectName(u"actionRotatedView")
        self.actionRotatedView.setCheckable(True)
        icon14 = QIcon()
        icon14.addFile(u"../../../axis/images/tool_axis_z2.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRotatedView.setIcon(icon14)
        self.actionSideView = QAction(MainWindow)
        self.actionSideView.setObjectName(u"actionSideView")
        self.actionSideView.setCheckable(True)
        icon15 = QIcon()
        icon15.addFile(u"../../../axis/images/tool_axis_x.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSideView.setIcon(icon15)
        self.actionFrontView = QAction(MainWindow)
        self.actionFrontView.setObjectName(u"actionFrontView")
        self.actionFrontView.setCheckable(True)
        icon16 = QIcon()
        icon16.addFile(u"../../../axis/images/tool_axis_y.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFrontView.setIcon(icon16)
        self.actionPerspectiveView = QAction(MainWindow)
        self.actionPerspectiveView.setObjectName(u"actionPerspectiveView")
        self.actionPerspectiveView.setCheckable(True)
        icon17 = QIcon()
        icon17.addFile(u"../../../axis/images/tool_axis_p.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPerspectiveView.setIcon(icon17)
        self.actionToolRotate = QAction(MainWindow)
        self.actionToolRotate.setObjectName(u"actionToolRotate")
        self.actionToolRotate.setCheckable(True)
        icon18 = QIcon()
        icon18.addFile(u"../../../axis/images/tool_rotate.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionToolRotate.setIcon(icon18)
        self.actionClearPlot = QAction(MainWindow)
        self.actionClearPlot.setObjectName(u"actionClearPlot")
        icon19 = QIcon()
        icon19.addFile(u"../../../axis/images/tool_clear.gif", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClearPlot.setIcon(icon19)
        self.actionClear_MDI_History = QAction(MainWindow)
        self.actionClear_MDI_History.setObjectName(u"actionClear_MDI_History")
        self.actionCalibration = QAction(MainWindow)
        self.actionCalibration.setObjectName(u"actionCalibration")
        self.actionHalshow = QAction(MainWindow)
        self.actionHalshow.setObjectName(u"actionHalshow")
        self.actionHalmeter = QAction(MainWindow)
        self.actionHalmeter.setObjectName(u"actionHalmeter")
        self.actionHalscope = QAction(MainWindow)
        self.actionHalscope.setObjectName(u"actionHalscope")
        self.actionStatus = QAction(MainWindow)
        self.actionStatus.setObjectName(u"actionStatus")
        self.actionRunFromLine = QAction(MainWindow)
        self.actionRunFromLine.setObjectName(u"actionRunFromLine")
        self.actionTouchoffWorkplace = QAction(MainWindow)
        self.actionTouchoffWorkplace.setObjectName(u"actionTouchoffWorkplace")
        self.actionTouchoffWorkplace.setCheckable(True)
        self.actionTouchoffFixture = QAction(MainWindow)
        self.actionTouchoffFixture.setObjectName(u"actionTouchoffFixture")
        self.actionTouchoffFixture.setCheckable(True)
        self.actionShutdown = QAction(MainWindow)
        self.actionShutdown.setObjectName(u"actionShutdown")
        self.actionToolOffsetDialog = QAction(MainWindow)
        self.actionToolOffsetDialog.setObjectName(u"actionToolOffsetDialog")
        icon20 = QIcon()
        icon20.addFile(u"../../../gmoccapy/images/editor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionToolOffsetDialog.setIcon(icon20)
        self.actionOriginOffsetDialog = QAction(MainWindow)
        self.actionOriginOffsetDialog.setObjectName(u"actionOriginOffsetDialog")
        self.actionOriginOffsetDialog.setIcon(icon20)
        self.actionMachineLog = QAction(MainWindow)
        self.actionMachineLog.setObjectName(u"actionMachineLog")
        self.actionShowOffsets = QAction(MainWindow)
        self.actionShowOffsets.setObjectName(u"actionShowOffsets")
        self.actionShowOffsets.setCheckable(True)
        self.actionCalculatorDialog = QAction(MainWindow)
        self.actionCalculatorDialog.setObjectName(u"actionCalculatorDialog")
        self.actionAlphaMode = QAction(MainWindow)
        self.actionAlphaMode.setObjectName(u"actionAlphaMode")
        self.actionAlphaMode.setCheckable(True)
        self.actionInhibitSelection = QAction(MainWindow)
        self.actionInhibitSelection.setObjectName(u"actionInhibitSelection")
        self.actionInhibitSelection.setCheckable(True)
        self.actionShow_G53_in_DRO = QAction(MainWindow)
        self.actionShow_G53_in_DRO.setObjectName(u"actionShow_G53_in_DRO")
        self.actionShow_G53_in_DRO.setCheckable(True)
        self.actionShow_G53_in_DRO.setChecked(True)
        self.actionVersaProbe = QAction(MainWindow)
        self.actionVersaProbe.setObjectName(u"actionVersaProbe")
        icon21 = QIcon()
        icon21.addFile(u"../../images/probe_icons/down.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionVersaProbe.setIcon(icon21)
        self.actionClearMessages = QAction(MainWindow)
        self.actionClearMessages.setObjectName(u"actionClearMessages")
        icon22 = QIcon(QIcon.fromTheme(u"error"))
        self.actionClearMessages.setIcon(icon22)
        self.actionShowMessages = QAction(MainWindow)
        self.actionShowMessages.setObjectName(u"actionShowMessages")
        icon23 = QIcon(QIcon.fromTheme(u"info"))
        self.actionShowMessages.setIcon(icon23)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_15 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, -1)
        self.screen_options = ScreenOptions(self.centralwidget)
        self.screen_options.setObjectName(u"screen_options")
        self.screen_options.setProperty("focusOverlay_option", True)
        self.screen_options.setProperty("entryDialog_option", True)
        self.screen_options.setProperty("entryDialogSoftkey_option", False)
        self.screen_options.setProperty("toolDialog_option", True)
        self.screen_options.setProperty("fileDialog_option", True)
        self.screen_options.setProperty("keyboardDialog_option", True)
        self.screen_options.setProperty("versaProbeDialog_option", True)
        self.screen_options.setProperty("toolOffsetDialog_option", True)
        self.screen_options.setProperty("originOffsetDialog_option", True)
        self.screen_options.setProperty("calculatorDialog_option", True)
        self.screen_options.setProperty("machineLogDialog_option", True)
        self.screen_options.setProperty("runFromLineDialog_option", True)
        self.horizontalLayout = QHBoxLayout(self.screen_options)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.allLayout = QHBoxLayout()
        self.allLayout.setSpacing(0)
        self.allLayout.setObjectName(u"allLayout")
        self.mainVLayout = QVBoxLayout()
        self.mainVLayout.setObjectName(u"mainVLayout")
        self.mainHLayout = QHBoxLayout()
        self.mainHLayout.setSpacing(0)
        self.mainHLayout.setObjectName(u"mainHLayout")
        self.frame = QFrame(self.screen_options)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(300, 0))
        self.frame.setMaximumSize(QSize(300, 16777215))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.verticalLayout_2 = QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.leftTab = QTabWidget(self.frame)
        self.leftTab.setObjectName(u"leftTab")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.leftTab.sizePolicy().hasHeightForWidth())
        self.leftTab.setSizePolicy(sizePolicy1)
        self.leftTab.setMinimumSize(QSize(300, 0))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayout_5 = QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 6, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setContentsMargins(6, -1, 6, -1)
        self.ras_3 = RadioAxisSelector(self.tab_3)
        self.ras_3.setObjectName(u"ras_3")
        self.ras_3.setMaximumSize(QSize(16777215, 20))
        self.ras_3.setChecked(False)
        self.ras_3.setProperty("joint_selection", 3)

        self.gridLayout.addWidget(self.ras_3, 1, 1, 1, 1)

        self.ras_2 = RadioAxisSelector(self.tab_3)
        self.ras_2.setObjectName(u"ras_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.ras_2.sizePolicy().hasHeightForWidth())
        self.ras_2.setSizePolicy(sizePolicy2)
        self.ras_2.setMaximumSize(QSize(16777215, 20))
        self.ras_2.setChecked(False)
        self.ras_2.setProperty("joint_selection", 2)

        self.gridLayout.addWidget(self.ras_2, 0, 5, 1, 1)

        self.ras_label_1 = QLabel(self.tab_3)
        self.ras_label_1.setObjectName(u"ras_label_1")
        sizePolicy.setHeightForWidth(self.ras_label_1.sizePolicy().hasHeightForWidth())
        self.ras_label_1.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.ras_label_1, 0, 4, 1, 1)

        self.ras_label_5 = QLabel(self.tab_3)
        self.ras_label_5.setObjectName(u"ras_label_5")
        self.ras_label_5.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_5, 1, 6, 1, 1)

        self.ras_1 = RadioAxisSelector(self.tab_3)
        self.ras_1.setObjectName(u"ras_1")
        sizePolicy2.setHeightForWidth(self.ras_1.sizePolicy().hasHeightForWidth())
        self.ras_1.setSizePolicy(sizePolicy2)
        self.ras_1.setMaximumSize(QSize(16777215, 20))
        self.ras_1.setChecked(False)
        self.ras_1.setProperty("joint_selection", 1)

        self.gridLayout.addWidget(self.ras_1, 0, 3, 1, 1)

        self.ras_label_3 = QLabel(self.tab_3)
        self.ras_label_3.setObjectName(u"ras_label_3")
        self.ras_label_3.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_3, 1, 2, 1, 1)

        self.ras_4 = RadioAxisSelector(self.tab_3)
        self.ras_4.setObjectName(u"ras_4")
        self.ras_4.setChecked(False)
        self.ras_4.setProperty("joint_selection", 4)

        self.gridLayout.addWidget(self.ras_4, 1, 3, 1, 1)

        self.ras_label_4 = QLabel(self.tab_3)
        self.ras_label_4.setObjectName(u"ras_label_4")
        self.ras_label_4.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_4, 1, 4, 1, 1)

        self.ras_label_2 = QLabel(self.tab_3)
        self.ras_label_2.setObjectName(u"ras_label_2")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.ras_label_2.sizePolicy().hasHeightForWidth())
        self.ras_label_2.setSizePolicy(sizePolicy3)
        self.ras_label_2.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_2, 0, 6, 1, 1)

        self.ras_5 = RadioAxisSelector(self.tab_3)
        self.ras_5.setObjectName(u"ras_5")
        self.ras_5.setMaximumSize(QSize(16777215, 20))
        self.ras_5.setChecked(False)
        self.ras_5.setProperty("joint_selection", 5)

        self.gridLayout.addWidget(self.ras_5, 1, 5, 1, 1)

        self.ras_label_title = QLabel(self.tab_3)
        self.ras_label_title.setObjectName(u"ras_label_title")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.ras_label_title.sizePolicy().hasHeightForWidth())
        self.ras_label_title.setSizePolicy(sizePolicy4)
        self.ras_label_title.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_title, 0, 0, 1, 1)

        self.ras_0 = RadioAxisSelector(self.tab_3)
        self.ras_0.setObjectName(u"ras_0")
        sizePolicy2.setHeightForWidth(self.ras_0.sizePolicy().hasHeightForWidth())
        self.ras_0.setSizePolicy(sizePolicy2)
        self.ras_0.setMaximumSize(QSize(16777215, 20))
        self.ras_0.setChecked(True)
        self.ras_0.setProperty("joint_selection", 0)

        self.gridLayout.addWidget(self.ras_0, 0, 1, 1, 1)

        self.ras_label_0 = QLabel(self.tab_3)
        self.ras_label_0.setObjectName(u"ras_label_0")
        sizePolicy.setHeightForWidth(self.ras_label_0.sizePolicy().hasHeightForWidth())
        self.ras_label_0.setSizePolicy(sizePolicy)
        self.ras_label_0.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_0, 0, 2, 1, 1)

        self.ras_label_6 = QLabel(self.tab_3)
        self.ras_label_6.setObjectName(u"ras_label_6")
        self.ras_label_6.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_6, 2, 2, 1, 1)

        self.ras_7 = RadioAxisSelector(self.tab_3)
        self.ras_7.setObjectName(u"ras_7")
        self.ras_7.setMaximumSize(QSize(16777215, 20))
        self.ras_7.setChecked(False)
        self.ras_7.setProperty("joint_selection", 7)

        self.gridLayout.addWidget(self.ras_7, 2, 3, 1, 1)

        self.ras_6 = RadioAxisSelector(self.tab_3)
        self.ras_6.setObjectName(u"ras_6")
        self.ras_6.setMaximumSize(QSize(16777215, 20))
        self.ras_6.setChecked(False)
        self.ras_6.setProperty("joint_selection", 6)

        self.gridLayout.addWidget(self.ras_6, 2, 1, 1, 1)

        self.ras_label_7 = QLabel(self.tab_3)
        self.ras_label_7.setObjectName(u"ras_label_7")
        self.ras_label_7.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_7, 2, 4, 1, 1)

        self.ras_label_8 = QLabel(self.tab_3)
        self.ras_label_8.setObjectName(u"ras_label_8")
        self.ras_label_8.setMaximumSize(QSize(16777215, 20))

        self.gridLayout.addWidget(self.ras_label_8, 2, 6, 1, 1)

        self.ras_8 = RadioAxisSelector(self.tab_3)
        self.ras_8.setObjectName(u"ras_8")
        self.ras_8.setMaximumSize(QSize(16777215, 20))
        self.ras_8.setChecked(False)
        self.ras_8.setProperty("joint_selection", 8)

        self.gridLayout.addWidget(self.ras_8, 2, 5, 1, 1)


        self.verticalLayout_5.addLayout(self.gridLayout)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(6, -1, 6, -1)
        self.actionButton_home = ActionButton(self.tab_3)
        self.actionButton_home.setObjectName(u"actionButton_home")
        sizePolicy2.setHeightForWidth(self.actionButton_home.sizePolicy().hasHeightForWidth())
        self.actionButton_home.setSizePolicy(sizePolicy2)
        self.actionButton_home.setMinimumSize(QSize(108, 0))
        self.actionButton_home.setMaximumSize(QSize(108, 20))
        self.actionButton_home.setProperty("home_action", True)
        self.actionButton_home.setProperty("joint_number", -1)
        self.actionButton_home.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionButton_home.setProperty("incr_mm_number", 0.025000000000000)
        self.actionButton_home.setProperty("incr_angular_number", -1.000000000000000)
        self.actionButton_home.setProperty("toggle_float_option", False)
        self.actionButton_home.setProperty("float_num", 100.000000000000000)
        self.actionButton_home.setProperty("float_alt_num", 50.000000000000000)
        self.actionButton_home.setProperty("ini_mdi_number", 0)

        self.gridLayout_2.addWidget(self.actionButton_home, 1, 0, 1, 1)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.actionbutton_2 = ActionButton(self.tab_3)
        self.actionbutton_2.setObjectName(u"actionbutton_2")
        self.actionbutton_2.setMaximumSize(QSize(50, 25))
        self.actionbutton_2.setProperty("jog_selected_pos_action", False)
        self.actionbutton_2.setProperty("jog_selected_neg_action", True)
        self.actionbutton_2.setProperty("joint_number", 0)
        self.actionbutton_2.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionbutton_2.setProperty("incr_mm_number", 0.025000000000000)
        self.actionbutton_2.setProperty("incr_angular_number", -1.000000000000000)
        self.actionbutton_2.setProperty("toggle_float_option", False)
        self.actionbutton_2.setProperty("float_num", 100.000000000000000)
        self.actionbutton_2.setProperty("float_alt_num", 50.000000000000000)
        self.actionbutton_2.setProperty("ini_mdi_number", 0)

        self.horizontalLayout_12.addWidget(self.actionbutton_2)

        self.actionbutton = ActionButton(self.tab_3)
        self.actionbutton.setObjectName(u"actionbutton")
        self.actionbutton.setMaximumSize(QSize(50, 25))
        self.actionbutton.setProperty("jog_selected_pos_action", True)
        self.actionbutton.setProperty("joint_number", 0)
        self.actionbutton.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionbutton.setProperty("incr_mm_number", 0.025000000000000)
        self.actionbutton.setProperty("incr_angular_number", -1.000000000000000)
        self.actionbutton.setProperty("toggle_float_option", False)
        self.actionbutton.setProperty("float_num", 100.000000000000000)
        self.actionbutton.setProperty("float_alt_num", 50.000000000000000)
        self.actionbutton.setProperty("ini_mdi_number", 0)

        self.horizontalLayout_12.addWidget(self.actionbutton)


        self.gridLayout_2.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)

        self.axistoolbutton = AxisToolButton(self.tab_3)
        self.axistoolbutton.setObjectName(u"axistoolbutton")
        self.axistoolbutton.setMinimumSize(QSize(100, 0))
        self.axistoolbutton.setMaximumSize(QSize(100, 25))
        self.axistoolbutton.setProperty("joint_number", -1)
        self.axistoolbutton.setProperty("halpin_option", False)

        self.gridLayout_2.addWidget(self.axistoolbutton, 1, 1, 1, 1)

        self.jogincrements = JogIncrements(self.tab_3)
        self.jogincrements.setObjectName(u"jogincrements")
        sizePolicy4.setHeightForWidth(self.jogincrements.sizePolicy().hasHeightForWidth())
        self.jogincrements.setSizePolicy(sizePolicy4)
        self.jogincrements.setMinimumSize(QSize(100, 0))
        self.jogincrements.setMaximumSize(QSize(100, 25))

        self.gridLayout_2.addWidget(self.jogincrements, 0, 1, 1, 1)

        self.actionbutton_7 = ActionButton(self.tab_3)
        self.actionbutton_7.setObjectName(u"actionbutton_7")
        self.actionbutton_7.setCheckable(True)
        self.actionbutton_7.setProperty("limits_override_action", True)

        self.gridLayout_2.addWidget(self.actionbutton_7, 2, 0, 1, 1)

        self.offsettoolbutton = OffsetToolButton(self.tab_3)
        self.offsettoolbutton.setObjectName(u"offsettoolbutton")
        self.offsettoolbutton.setPopupMode(QToolButton.InstantPopup)

        self.gridLayout_2.addWidget(self.offsettoolbutton, 2, 1, 1, 1)


        self.verticalLayout_5.addLayout(self.gridLayout_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(6, -1, 6, -1)
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMaximumSize(QSize(16777215, 35))

        self.horizontalLayout_4.addWidget(self.label_7)

        self.actionbutton_4 = ActionButton(self.tab_3)
        self.actionbutton_4.setObjectName(u"actionbutton_4")
        self.actionbutton_4.setMaximumSize(QSize(50, 25))
        icon24 = QIcon()
        icon24.addFile(u"../../../axis/images/spindle_ccw.gif", QSize(), QIcon.Selected, QIcon.On)
        self.actionbutton_4.setIcon(icon24)
        self.actionbutton_4.setProperty("spindle_rev_action", False)
        self.actionbutton_4.setProperty("spindle_down_action", True)
        self.actionbutton_4.setProperty("joint_number", 0)
        self.actionbutton_4.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionbutton_4.setProperty("incr_mm_number", 0.025000000000000)
        self.actionbutton_4.setProperty("incr_angular_number", -1.000000000000000)
        self.actionbutton_4.setProperty("toggle_float_option", False)
        self.actionbutton_4.setProperty("float_num", 100.000000000000000)
        self.actionbutton_4.setProperty("float_alt_num", 50.000000000000000)
        self.actionbutton_4.setProperty("ini_mdi_number", 0)

        self.horizontalLayout_4.addWidget(self.actionbutton_4)

        self.actionbutton_5 = ActionButton(self.tab_3)
        self.actionbutton_5.setObjectName(u"actionbutton_5")
        self.actionbutton_5.setMaximumSize(QSize(50, 25))
        self.actionbutton_5.setCheckable(False)
        self.actionbutton_5.setChecked(False)
        self.actionbutton_5.setProperty("spindle_stop_action", True)
        self.actionbutton_5.setProperty("joint_number", 0)
        self.actionbutton_5.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionbutton_5.setProperty("incr_mm_number", 0.025000000000000)
        self.actionbutton_5.setProperty("incr_angular_number", -1.000000000000000)
        self.actionbutton_5.setProperty("toggle_float_option", False)
        self.actionbutton_5.setProperty("float_num", 100.000000000000000)
        self.actionbutton_5.setProperty("float_alt_num", 50.000000000000000)
        self.actionbutton_5.setProperty("ini_mdi_number", 0)

        self.horizontalLayout_4.addWidget(self.actionbutton_5)

        self.actionbutton_6 = ActionButton(self.tab_3)
        self.actionbutton_6.setObjectName(u"actionbutton_6")
        self.actionbutton_6.setMaximumSize(QSize(50, 25))
        icon25 = QIcon()
        icon25.addFile(u"../../../axis/images/spindle_cw.gif", QSize(), QIcon.Selected, QIcon.On)
        self.actionbutton_6.setIcon(icon25)
        self.actionbutton_6.setProperty("spindle_fwd_action", False)
        self.actionbutton_6.setProperty("spindle_up_action", True)
        self.actionbutton_6.setProperty("joint_number", 0)
        self.actionbutton_6.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionbutton_6.setProperty("incr_mm_number", 0.025000000000000)
        self.actionbutton_6.setProperty("incr_angular_number", -1.000000000000000)
        self.actionbutton_6.setProperty("toggle_float_option", False)
        self.actionbutton_6.setProperty("float_num", 100.000000000000000)
        self.actionbutton_6.setProperty("float_alt_num", 50.000000000000000)
        self.actionbutton_6.setProperty("ini_mdi_number", 0)

        self.horizontalLayout_4.addWidget(self.actionbutton_6)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer)


        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.leftTab.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.verticalLayout_4 = QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 0)
        self.mdihistory = MDIHistory(self.tab_4)
        self.mdihistory.setObjectName(u"mdihistory")
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.MinimumExpanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.mdihistory.sizePolicy().hasHeightForWidth())
        self.mdihistory.setSizePolicy(sizePolicy5)
        self.mdihistory.setMinimumSize(QSize(200, 75))

        self.verticalLayout_4.addWidget(self.mdihistory)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.statuslabel_8 = StatusLabel(self.tab_4)
        self.statuslabel_8.setObjectName(u"statuslabel_8")
        self.statuslabel_8.setProperty("fcode_status", True)
        self.statuslabel_8.setProperty("mcodes_status", False)

        self.horizontalLayout_11.addWidget(self.statuslabel_8)

        self.statuslabel_2 = StatusLabel(self.tab_4)
        self.statuslabel_2.setObjectName(u"statuslabel_2")
        self.statuslabel_2.setProperty("mcodes_status", True)

        self.horizontalLayout_11.addWidget(self.statuslabel_2)


        self.verticalLayout_4.addLayout(self.horizontalLayout_11)

        self.statuslabel = StatusLabel(self.tab_4)
        self.statuslabel.setObjectName(u"statuslabel")
        self.statuslabel.setScaledContents(True)
        self.statuslabel.setWordWrap(True)
        self.statuslabel.setProperty("gcodes_status", True)

        self.verticalLayout_4.addWidget(self.statuslabel)

        self.leftTab.addTab(self.tab_4, "")

        self.verticalLayout_2.addWidget(self.leftTab)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_4)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")

        self.verticalLayout_2.addLayout(self.horizontalLayout_13)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMargin(-10)

        self.horizontalLayout_5.addWidget(self.label_6)

        self.statuslabel_3 = StatusLabel(self.frame)
        self.statuslabel_3.setObjectName(u"statuslabel_3")
        self.statuslabel_3.setMaximumSize(QSize(50, 16777215))
        self.statuslabel_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.statuslabel_3.setMargin(-7)

        self.horizontalLayout_5.addWidget(self.statuslabel_3)

        self.statusslider = StatusSlider(self.frame)
        self.statusslider.setObjectName(u"statusslider")
        self.statusslider.setMaximumSize(QSize(125, 16777215))
        self.statusslider.setOrientation(Qt.Horizontal)
        self.statusslider.setProperty("rapid_rate", False)
        self.statusslider.setProperty("feed_rate", True)

        self.horizontalLayout_5.addWidget(self.statusslider)


        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMargin(-10)

        self.horizontalLayout_6.addWidget(self.label_8)

        self.statuslabel_4 = StatusLabel(self.frame)
        self.statuslabel_4.setObjectName(u"statuslabel_4")
        self.statuslabel_4.setMaximumSize(QSize(50, 16777215))
        self.statuslabel_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.statuslabel_4.setMargin(-7)
        self.statuslabel_4.setProperty("rapid_override_status", True)

        self.horizontalLayout_6.addWidget(self.statuslabel_4)

        self.statusslider_2 = StatusSlider(self.frame)
        self.statusslider_2.setObjectName(u"statusslider_2")
        self.statusslider_2.setMaximumSize(QSize(125, 16777215))
        self.statusslider_2.setOrientation(Qt.Horizontal)

        self.horizontalLayout_6.addWidget(self.statusslider_2)


        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMargin(-10)

        self.horizontalLayout_7.addWidget(self.label_9)

        self.statuslabel_5 = StatusLabel(self.frame)
        self.statuslabel_5.setObjectName(u"statuslabel_5")
        self.statuslabel_5.setMaximumSize(QSize(50, 16777215))
        self.statuslabel_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.statuslabel_5.setMargin(-7)
        self.statuslabel_5.setProperty("spindle_override_status", True)

        self.horizontalLayout_7.addWidget(self.statuslabel_5)

        self.statusslider_3 = StatusSlider(self.frame)
        self.statusslider_3.setObjectName(u"statusslider_3")
        self.statusslider_3.setMaximumSize(QSize(125, 16777215))
        self.statusslider_3.setOrientation(Qt.Horizontal)
        self.statusslider_3.setProperty("rapid_rate", False)
        self.statusslider_3.setProperty("spindle_rate", True)

        self.horizontalLayout_7.addWidget(self.statusslider_3)


        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setMargin(-10)

        self.horizontalLayout_8.addWidget(self.label_10)

        self.statuslabel_6 = StatusLabel(self.frame)
        self.statuslabel_6.setObjectName(u"statuslabel_6")
        self.statuslabel_6.setMaximumSize(QSize(50, 16777215))
        self.statuslabel_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.statuslabel_6.setMargin(-7)
        self.statuslabel_6.setProperty("jograte_status", True)

        self.horizontalLayout_8.addWidget(self.statuslabel_6)

        self.statusslider_4 = StatusSlider(self.frame)
        self.statusslider_4.setObjectName(u"statusslider_4")
        self.statusslider_4.setMaximumSize(QSize(125, 16777215))
        self.statusslider_4.setOrientation(Qt.Horizontal)
        self.statusslider_4.setProperty("rapid_rate", False)
        self.statusslider_4.setProperty("jograte_rate", True)

        self.horizontalLayout_8.addWidget(self.statusslider_4)


        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMargin(-10)

        self.horizontalLayout_9.addWidget(self.label_11)

        self.statuslabel_7 = StatusLabel(self.frame)
        self.statuslabel_7.setObjectName(u"statuslabel_7")
        self.statuslabel_7.setMaximumSize(QSize(50, 16777215))
        self.statuslabel_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.statuslabel_7.setMargin(-7)
        self.statuslabel_7.setProperty("max_velocity_override_status", True)

        self.horizontalLayout_9.addWidget(self.statuslabel_7)

        self.statusslider_5 = StatusSlider(self.frame)
        self.statusslider_5.setObjectName(u"statusslider_5")
        self.statusslider_5.setMaximumSize(QSize(125, 16777215))
        self.statusslider_5.setOrientation(Qt.Horizontal)
        self.statusslider_5.setProperty("rapid_rate", False)
        self.statusslider_5.setProperty("jograte_angular_rate", False)
        self.statusslider_5.setProperty("max_velocity_rate", True)

        self.horizontalLayout_9.addWidget(self.statusslider_5)


        self.verticalLayout_2.addLayout(self.horizontalLayout_9)


        self.mainHLayout.addWidget(self.frame)

        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.rightTab = DetachTabWidget(self.screen_options)
        self.rightTab.setObjectName(u"rightTab")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_8 = QVBoxLayout(self.tab)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.gridLayout_3 = QGridLayout(self.frame_2)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.dro_label_g5x_x = DROLabel(self.frame_2)
        self.dro_label_g5x_x.setObjectName(u"dro_label_g5x_x")
        sizePolicy4.setHeightForWidth(self.dro_label_g5x_x.sizePolicy().hasHeightForWidth())
        self.dro_label_g5x_x.setSizePolicy(sizePolicy4)
        self.dro_label_g5x_x.setTextFormat(Qt.PlainText)
        self.dro_label_g5x_x.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dro_label_g5x_x.setProperty("Qreference_type", 1)

        self.horizontalLayout_14.addWidget(self.dro_label_g5x_x)

        self.horizontalLayout_14.setStretch(0, 1)

        self.gridLayout_3.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)

        self.horizontalLayout_19 = QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.dro_label_g5x_z = DROLabel(self.frame_2)
        self.dro_label_g5x_z.setObjectName(u"dro_label_g5x_z")
        sizePolicy4.setHeightForWidth(self.dro_label_g5x_z.sizePolicy().hasHeightForWidth())
        self.dro_label_g5x_z.setSizePolicy(sizePolicy4)
        self.dro_label_g5x_z.setTextFormat(Qt.PlainText)
        self.dro_label_g5x_z.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dro_label_g5x_z.setProperty("Qjoint_number", 2)
        self.dro_label_g5x_z.setProperty("Qreference_type", 1)

        self.horizontalLayout_19.addWidget(self.dro_label_g5x_z)


        self.gridLayout_3.addLayout(self.horizontalLayout_19, 5, 0, 1, 1)

        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.dro_label_g5x_r = DROLabel(self.frame_2)
        self.dro_label_g5x_r.setObjectName(u"dro_label_g5x_r")
        sizePolicy4.setHeightForWidth(self.dro_label_g5x_r.sizePolicy().hasHeightForWidth())
        self.dro_label_g5x_r.setSizePolicy(sizePolicy4)
        self.dro_label_g5x_r.setTextFormat(Qt.PlainText)
        self.dro_label_g5x_r.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dro_label_g5x_r.setProperty("Qjoint_number", 10)
        self.dro_label_g5x_r.setProperty("Qreference_type", 0)

        self.horizontalLayout_20.addWidget(self.dro_label_g5x_r)


        self.gridLayout_3.addLayout(self.horizontalLayout_20, 6, 0, 1, 1)

        self.widget_dro_g53 = QWidget(self.frame_2)
        self.widget_dro_g53.setObjectName(u"widget_dro_g53")
        sizePolicy4.setHeightForWidth(self.widget_dro_g53.sizePolicy().hasHeightForWidth())
        self.widget_dro_g53.setSizePolicy(sizePolicy4)
        self.verticalLayout_3 = QVBoxLayout(self.widget_dro_g53)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.horizontalLayout_g53_x = QHBoxLayout()
        self.horizontalLayout_g53_x.setSpacing(0)
        self.horizontalLayout_g53_x.setObjectName(u"horizontalLayout_g53_x")
        self.dro_label_g53_x = DROLabel(self.widget_dro_g53)
        self.dro_label_g53_x.setObjectName(u"dro_label_g53_x")
        sizePolicy4.setHeightForWidth(self.dro_label_g53_x.sizePolicy().hasHeightForWidth())
        self.dro_label_g53_x.setSizePolicy(sizePolicy4)

        self.horizontalLayout_g53_x.addWidget(self.dro_label_g53_x)


        self.verticalLayout_6.addLayout(self.horizontalLayout_g53_x)

        self.dro_absolute_y = QWidget(self.widget_dro_g53)
        self.dro_absolute_y.setObjectName(u"dro_absolute_y")
        self.horizontalLayout_g53_y = QHBoxLayout(self.dro_absolute_y)
        self.horizontalLayout_g53_y.setSpacing(0)
        self.horizontalLayout_g53_y.setObjectName(u"horizontalLayout_g53_y")
        self.horizontalLayout_g53_y.setContentsMargins(0, 0, 0, 0)
        self.dro_label_g53_y = DROLabel(self.dro_absolute_y)
        self.dro_label_g53_y.setObjectName(u"dro_label_g53_y")
        sizePolicy4.setHeightForWidth(self.dro_label_g53_y.sizePolicy().hasHeightForWidth())
        self.dro_label_g53_y.setSizePolicy(sizePolicy4)
        self.dro_label_g53_y.setProperty("Qjoint_number", 1)

        self.horizontalLayout_g53_y.addWidget(self.dro_label_g53_y)


        self.verticalLayout_6.addWidget(self.dro_absolute_y)

        self.horizontalLayout_g53_z = QHBoxLayout()
        self.horizontalLayout_g53_z.setSpacing(0)
        self.horizontalLayout_g53_z.setObjectName(u"horizontalLayout_g53_z")
        self.dro_label_g53_z = DROLabel(self.widget_dro_g53)
        self.dro_label_g53_z.setObjectName(u"dro_label_g53_z")
        sizePolicy4.setHeightForWidth(self.dro_label_g53_z.sizePolicy().hasHeightForWidth())
        self.dro_label_g53_z.setSizePolicy(sizePolicy4)
        self.dro_label_g53_z.setProperty("Qjoint_number", 2)

        self.horizontalLayout_g53_z.addWidget(self.dro_label_g53_z)


        self.verticalLayout_6.addLayout(self.horizontalLayout_g53_z)


        self.verticalLayout_3.addLayout(self.verticalLayout_6)


        self.gridLayout_3.addWidget(self.widget_dro_g53, 0, 0, 1, 1)

        self.dro_relative_y = QWidget(self.frame_2)
        self.dro_relative_y.setObjectName(u"dro_relative_y")
        self.horizontalLayout_18 = QHBoxLayout(self.dro_relative_y)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.dro_label_g5x_y = DROLabel(self.dro_relative_y)
        self.dro_label_g5x_y.setObjectName(u"dro_label_g5x_y")
        sizePolicy4.setHeightForWidth(self.dro_label_g5x_y.sizePolicy().hasHeightForWidth())
        self.dro_label_g5x_y.setSizePolicy(sizePolicy4)
        self.dro_label_g5x_y.setTextFormat(Qt.PlainText)
        self.dro_label_g5x_y.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dro_label_g5x_y.setProperty("Qjoint_number", 1)
        self.dro_label_g5x_y.setProperty("Qreference_type", 1)

        self.horizontalLayout_18.addWidget(self.dro_label_g5x_y)


        self.gridLayout_3.addWidget(self.dro_relative_y, 4, 0, 1, 1)


        self.verticalLayout_8.addWidget(self.frame_2)

        self.rightTab.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout = QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.gcodegraphics = GCodeGraphics(self.tab_2)
        self.gcodegraphics.setObjectName(u"gcodegraphics")
        self.gcodegraphics.setProperty("_dro", True)
        self.gcodegraphics.setProperty("_dtg", False)
        self.gcodegraphics.setProperty("background_color", QColor(0, 0, 0))
        self.gcodegraphics.setProperty("overlay", True)

        self.verticalLayout.addWidget(self.gcodegraphics)

        self.rightTab.addTab(self.tab_2, "")

        self.verticalLayout_7.addWidget(self.rightTab)


        self.mainHLayout.addLayout(self.verticalLayout_7)


        self.mainVLayout.addLayout(self.mainHLayout)

        self.gcode_editor = GcodeEditor(self.screen_options)
        self.gcode_editor.setObjectName(u"gcode_editor")
        sizePolicy5.setHeightForWidth(self.gcode_editor.sizePolicy().hasHeightForWidth())
        self.gcode_editor.setSizePolicy(sizePolicy5)
        self.gcode_editor.setMinimumSize(QSize(300, 100))
        self.gcode_editor.setMaximumSize(QSize(16777215, 500))
        self.gcode_editor.setProperty("auto_show_mdi_status", False)

        self.mainVLayout.addWidget(self.gcode_editor)


        self.allLayout.addLayout(self.mainVLayout)

        self.rightPanel = QStackedWidget(self.screen_options)
        self.rightPanel.setObjectName(u"rightPanel")
        sizePolicy6 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.rightPanel.sizePolicy().hasHeightForWidth())
        self.rightPanel.setSizePolicy(sizePolicy6)
        self.rightPanel.setMaximumSize(QSize(0, 16777215))

        self.allLayout.addWidget(self.rightPanel)


        self.horizontalLayout.addLayout(self.allLayout)


        self.horizontalLayout_15.addWidget(self.screen_options)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 802, 27))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecent = QMenu(self.menuFile)
        self.menuRecent.setObjectName(u"menuRecent")
        self.menuMachine = QMenu(self.menubar)
        self.menuMachine.setObjectName(u"menuMachine")
        self.menuHoming = QMenu(self.menuMachine)
        self.menuHoming.setObjectName(u"menuHoming")
        self.menuUnhome = QMenu(self.menuMachine)
        self.menuUnhome.setObjectName(u"menuUnhome")
        self.menuZeroCoordinateSystem = QMenu(self.menuMachine)
        self.menuZeroCoordinateSystem.setObjectName(u"menuZeroCoordinateSystem")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuGridSize = QMenu(self.menuView)
        self.menuGridSize.setObjectName(u"menuGridSize")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuStstem = QMenu(self.menubar)
        self.menuStstem.setObjectName(u"menuStstem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMachine.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuStstem.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addAction(self.actionReload)
        self.menuFile.addAction(self.actionEdit)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionProperties)
        self.menuFile.addAction(self.actionToolOffsetDialog)
        self.menuFile.addAction(self.actionOriginOffsetDialog)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuMachine.addAction(self.actionClear_MDI_History)
        self.menuMachine.addAction(self.actionCalibration)
        self.menuMachine.addAction(self.actionHalshow)
        self.menuMachine.addAction(self.actionHalmeter)
        self.menuMachine.addAction(self.actionHalscope)
        self.menuMachine.addAction(self.actionStatus)
        self.menuMachine.addAction(self.menuHoming.menuAction())
        self.menuMachine.addAction(self.menuUnhome.menuAction())
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.actionVersaProbe)
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.actionEstop)
        self.menuMachine.addAction(self.actionMachineOn)
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.actionRun)
        self.menuMachine.addAction(self.actionRunFromLine)
        self.menuMachine.addAction(self.actionStep)
        self.menuMachine.addAction(self.actionPause)
        self.menuMachine.addAction(self.actionStop)
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.actionOptionalStop)
        self.menuMachine.addAction(self.actionSkip)
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.menuZeroCoordinateSystem.menuAction())
        self.menuMachine.addAction(self.actionTouchoffWorkplace)
        self.menuMachine.addAction(self.actionTouchoffFixture)
        self.menuView.addAction(self.actionPerspectiveView)
        self.menuView.addAction(self.actionSideView)
        self.menuView.addAction(self.actionFrontView)
        self.menuView.addAction(self.actionTopView)
        self.menuView.addAction(self.actionRotatedView)
        self.menuView.addAction(self.actionClearPlot)
        self.menuView.addAction(self.actionShowOffsets)
        self.menuView.addAction(self.actionShow_G53_in_DRO)
        self.menuView.addAction(self.menuGridSize.menuAction())
        self.menuView.addAction(self.actionAlphaMode)
        self.menuView.addAction(self.actionInhibitSelection)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionQuickRef)
        self.menuHelp.addAction(self.actionMachineLog)
        self.menuHelp.addAction(self.actionCalculatorDialog)
        self.menuStstem.addAction(self.actionShutdown)
        self.toolBar.addAction(self.actionEstop)
        self.toolBar.addAction(self.actionMachineOn)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSkip)
        self.toolBar.addAction(self.actionOptionalStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoomOut)
        self.toolBar.addAction(self.actionTopView)
        self.toolBar.addAction(self.actionRotatedView)
        self.toolBar.addAction(self.actionSideView)
        self.toolBar.addAction(self.actionFrontView)
        self.toolBar.addAction(self.actionPerspectiveView)
        self.toolBar.addAction(self.actionClearMessages)
        self.toolBar.addAction(self.actionShowMessages)
        self.toolBar.addAction(self.actionClearPlot)

        self.retranslateUi(MainWindow)
        self.leftTab.currentChanged.connect(MainWindow.leftTabChanged)
        self.gcode_editor.percentDone.connect(MainWindow.percentCompleted)

        self.leftTab.setCurrentIndex(0)
        self.rightTab.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionQuickRef.setText(QCoreApplication.translate("MainWindow", u"Quick Reference", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionReload.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionProperties.setText(QCoreApplication.translate("MainWindow", u"Properties", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionEstop.setText(QCoreApplication.translate("MainWindow", u"Estop", None))
        self.actionMachineOn.setText(QCoreApplication.translate("MainWindow", u"Machine On", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.actionStep.setText(QCoreApplication.translate("MainWindow", u"Step", None))
        self.actionPause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.actionSkip.setText(QCoreApplication.translate("MainWindow", u"Skip", None))
        self.actionOptionalStop.setText(QCoreApplication.translate("MainWindow", u"Optional Stop", None))
        self.actionZoomIn.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
        self.actionZoomOut.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
        self.actionTopView.setText(QCoreApplication.translate("MainWindow", u"Top View", None))
        self.actionRotatedView.setText(QCoreApplication.translate("MainWindow", u"Rotated View", None))
        self.actionSideView.setText(QCoreApplication.translate("MainWindow", u"Side View", None))
        self.actionFrontView.setText(QCoreApplication.translate("MainWindow", u"Front View", None))
        self.actionPerspectiveView.setText(QCoreApplication.translate("MainWindow", u"Perspective View", None))
        self.actionToolRotate.setText(QCoreApplication.translate("MainWindow", u"Tool Rotate", None))
        self.actionClearPlot.setText(QCoreApplication.translate("MainWindow", u"Clear Plot", None))
        self.actionClear_MDI_History.setText(QCoreApplication.translate("MainWindow", u"Clear MDI History", None))
        self.actionCalibration.setText(QCoreApplication.translate("MainWindow", u"Calibration", None))
        self.actionHalshow.setText(QCoreApplication.translate("MainWindow", u"Show HAL Configuration", None))
        self.actionHalmeter.setText(QCoreApplication.translate("MainWindow", u"HAl meter", None))
        self.actionHalscope.setText(QCoreApplication.translate("MainWindow", u"HAl Scope", None))
        self.actionStatus.setText(QCoreApplication.translate("MainWindow", u"Linuxcnc Status", None))
        self.actionRunFromLine.setText(QCoreApplication.translate("MainWindow", u"Run From Line", None))
        self.actionTouchoffWorkplace.setText(QCoreApplication.translate("MainWindow", u"Touchoff Workplace", None))
        self.actionTouchoffFixture.setText(QCoreApplication.translate("MainWindow", u"Touchoff Fixture", None))
        self.actionShutdown.setText(QCoreApplication.translate("MainWindow", u"Shutdown", None))
#if QT_CONFIG(tooltip)
        self.actionShutdown.setToolTip(QCoreApplication.translate("MainWindow", u"Shutdown System Immediately", None))
#endif // QT_CONFIG(tooltip)
        self.actionToolOffsetDialog.setText(QCoreApplication.translate("MainWindow", u"Edit tooltable", None))
        self.actionOriginOffsetDialog.setText(QCoreApplication.translate("MainWindow", u"View Origintable", None))
        self.actionMachineLog.setText(QCoreApplication.translate("MainWindow", u"Machine Log", None))
        self.actionShowOffsets.setText(QCoreApplication.translate("MainWindow", u"Show Offsets", None))
        self.actionCalculatorDialog.setText(QCoreApplication.translate("MainWindow", u"Calculator", None))
        self.actionAlphaMode.setText(QCoreApplication.translate("MainWindow", u"Alpha Mode", None))
        self.actionInhibitSelection.setText(QCoreApplication.translate("MainWindow", u"Inhibit Selection", None))
        self.actionShow_G53_in_DRO.setText(QCoreApplication.translate("MainWindow", u"Show G53 in DRO", None))
        self.actionVersaProbe.setText(QCoreApplication.translate("MainWindow", u"Versa Probe", None))
#if QT_CONFIG(tooltip)
        self.actionVersaProbe.setToolTip(QCoreApplication.translate("MainWindow", u"Versa Probe Dialog", None))
#endif // QT_CONFIG(tooltip)
        self.actionClearMessages.setText(QCoreApplication.translate("MainWindow", u"Clear messages", None))
#if QT_CONFIG(tooltip)
        self.actionClearMessages.setToolTip(QCoreApplication.translate("MainWindow", u"Clear Messages", None))
#endif // QT_CONFIG(tooltip)
        self.actionShowMessages.setText(QCoreApplication.translate("MainWindow", u"Show messages", None))
#if QT_CONFIG(tooltip)
        self.actionShowMessages.setToolTip(QCoreApplication.translate("MainWindow", u"Show messages", None))
#endif // QT_CONFIG(tooltip)
        self.screen_options.setProperty("default_embed_tab", QCoreApplication.translate("MainWindow", u"rightTab", None))
        self.ras_3.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"A", None))
        self.ras_2.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"Z", None))
        self.ras_label_1.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.ras_label_5.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.ras_1.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"Y", None))
        self.ras_label_3.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.ras_4.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"B", None))
        self.ras_label_4.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.ras_label_2.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.ras_5.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"C", None))
        self.ras_label_title.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">Axis</span></p></body></html>", None))
        self.ras_0.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"X", None))
        self.ras_label_0.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.ras_label_6.setText(QCoreApplication.translate("MainWindow", u"U", None))
        self.ras_7.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"V", None))
        self.ras_6.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"U", None))
        self.ras_label_7.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.ras_label_8.setText(QCoreApplication.translate("MainWindow", u"W", None))
        self.ras_8.setProperty("axis_selection", QCoreApplication.translate("MainWindow", u"W", None))
        self.actionButton_home.setText(QCoreApplication.translate("MainWindow", u"Home All", None))
        self.actionButton_home.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"P", None))
        self.actionButton_home.setProperty("command_text_string", "")
        self.actionbutton_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.actionbutton_2.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"P", None))
        self.actionbutton_2.setProperty("command_text_string", "")
        self.actionbutton.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.actionbutton.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"P", None))
        self.actionbutton.setProperty("command_text_string", "")
        self.axistoolbutton.setText(QCoreApplication.translate("MainWindow", u"Set Origin", None))
        self.actionbutton_7.setText(QCoreApplication.translate("MainWindow", u"Override Limits", None))
        self.offsettoolbutton.setText(QCoreApplication.translate("MainWindow", u"Set Tool Offset", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">Spindle:</span></p></body></html>", None))
        self.actionbutton_4.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"P", None))
        self.actionbutton_4.setProperty("command_text_string", "")
        self.actionbutton_5.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.actionbutton_5.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"P", None))
        self.actionbutton_5.setProperty("command_text_string", "")
        self.actionbutton_6.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"P", None))
        self.actionbutton_6.setProperty("command_text_string", "")
        self.leftTab.setTabText(self.leftTab.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Manual Control [F3]", None))
        self.statuslabel_8.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">ACTIVE: </span>F %0.1f</p></body></html>", None))
        self.leftTab.setTabText(self.leftTab.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"MDI [F5]", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Feed Override:    ", None))
        self.statuslabel_3.setText(QCoreApplication.translate("MainWindow", u"100.0", None))
        self.statuslabel_3.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"%s", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Rapid Override:    ", None))
        self.statuslabel_4.setText(QCoreApplication.translate("MainWindow", u"100.0", None))
        self.statuslabel_4.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"%s", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Spindle Override:    ", None))
        self.statuslabel_5.setText(QCoreApplication.translate("MainWindow", u"100.0", None))
        self.statuslabel_5.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"%s", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Jog Rate:", None))
        self.statuslabel_6.setText(QCoreApplication.translate("MainWindow", u"100.0", None))
        self.statuslabel_6.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"%s", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Max Velocity", None))
        self.statuslabel_7.setText(QCoreApplication.translate("MainWindow", u"100.0", None))
        self.statuslabel_7.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"%s", None))
        self.dro_label_g5x_x.setText(QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_x.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"X %10.3f", None))
        self.dro_label_g5x_x.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"X %9.4f", None))
        self.dro_label_g5x_z.setText(QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_z.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_z.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"%9.4f", None))
        self.dro_label_g5x_r.setText(QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_r.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_r.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"%9.4f", None))
        self.dro_label_g5x_r.setProperty("angular_template", QCoreApplication.translate("MainWindow", u"%4.2f", None))
        self.dro_label_g53_x.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"X %10.3f", None))
        self.dro_label_g53_x.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"X %9.4f", None))
        self.dro_label_g53_y.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"Y %10.3f", None))
        self.dro_label_g53_y.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"Y %9.4f", None))
        self.dro_label_g53_z.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"Z %10.3f", None))
        self.dro_label_g53_z.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"Z %9.4f", None))
        self.dro_label_g5x_y.setText(QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_y.setProperty("metric_template", QCoreApplication.translate("MainWindow", u"%10.3f", None))
        self.dro_label_g5x_y.setProperty("imperial_template", QCoreApplication.translate("MainWindow", u"%9.4f", None))
        self.rightTab.setTabText(self.rightTab.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"DRO", None))
        self.gcodegraphics.setProperty("_view", QCoreApplication.translate("MainWindow", u"p", None))
        self.rightTab.setTabText(self.rightTab.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Preview", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRecent.setTitle(QCoreApplication.translate("MainWindow", u"Recent", None))
        self.menuMachine.setTitle(QCoreApplication.translate("MainWindow", u"Machine", None))
        self.menuHoming.setTitle(QCoreApplication.translate("MainWindow", u"Homing", None))
        self.menuUnhome.setTitle(QCoreApplication.translate("MainWindow", u"Unhome ", None))
        self.menuZeroCoordinateSystem.setTitle(QCoreApplication.translate("MainWindow", u"Zero Coordinate System", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuGridSize.setTitle(QCoreApplication.translate("MainWindow", u"Grid Size", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuStstem.setTitle(QCoreApplication.translate("MainWindow", u"System", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

