# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qtdefault_ngc.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from qtvcp.widgets.gcode_graphics import GCodeGraphics
from qtvcp.widgets.dialog_widget import CamViewDialog
from qtvcp.widgets.dialog_widget import LcncDialog
from qtvcp.widgets.status_slider import StatusSlider
from qtvcp.widgets.mdi_line import MDILine
from qtvcp.widgets.xembed import XEmbed
from qtvcp.widgets.state_label import StateLabel
from qtvcp.widgets.led_widget import LED
from qtvcp.widgets.dialog_widget import MacroTabDialog
from qtvcp.widgets.state_led import StateLED
from qtvcp.widgets.dialog_widget import OriginOffsetDialog
from qtvcp.widgets.container_widgets import StateEnableGridLayout
from qtvcp.widgets.status_stacked import StatusStacked
from qtvcp.widgets.dialog_widget import ToolOffsetDialog
from qtvcp.widgets.jog_increments import JogIncrements
from qtvcp.widgets.dialog_widget import FileDialog
from qtvcp.widgets.overlay_widget import FocusOverlay
from qtvcp.widgets.screen_options import ScreenOptions
from qtvcp.widgets.status_label import StatusLabel
from qtvcp.widgets.dro_widget import DROLabel
from qtvcp.widgets.gcode_editor import GcodeEditor
from qtvcp.widgets.action_button import ActionButton
from qtvcp.widgets.dialog_widget import ToolDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1791, 790)
        MainWindow.setMinimumSize(QSize(1027, 790))
        MainWindow.setMaximumSize(QSize(10270, 790))
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.drolabel_y = DROLabel(self.centralwidget)
        self.drolabel_y.setObjectName(u"drolabel_y")
        self.drolabel_y.setGeometry(QRect(450, 520, 131, 21))
        self.drolabel_y.setStyleSheet(u"color: rgb(0, 255, 255);\n"
"font: 75 18pt \"Courier 10 Pitch\";")
        self.drolabel_y.setProperty("Qjoint_number", 1)
        self.drolabel_y.setProperty("Qreference_type", 0)
        self.drolabel_z = DROLabel(self.centralwidget)
        self.drolabel_z.setObjectName(u"drolabel_z")
        self.drolabel_z.setGeometry(QRect(450, 550, 131, 21))
        self.drolabel_z.setStyleSheet(u"color: rgb(0, 255, 255);\n"
"font: 18pt \"Courier 10 Pitch\";")
        self.drolabel_z.setTextFormat(Qt.PlainText)
        self.drolabel_z.setScaledContents(True)
        self.drolabel_z.setProperty("Qjoint_number", 2)
        self.drolabel_z.setProperty("Qreference_type", 0)
        self.drolabel_x = DROLabel(self.centralwidget)
        self.drolabel_x.setObjectName(u"drolabel_x")
        self.drolabel_x.setGeometry(QRect(450, 490, 131, 21))
        self.drolabel_x.setStyleSheet(u"color: rgb(0, 255, 255);\n"
"font: 75 18pt \"Courier 10 Pitch\";")
        self.drolabel_x.setProperty("Qreference_type", 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(True)
        self.frame.setGeometry(QRect(210, 10, 811, 231))
        self.frame.setStyleSheet(u"#frame{\n"
"border-image: url(/home/chris/emc-dev/configs/sim/qtscreen/backgound_blue.png) 0 0 0 0 stretch stretch;}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.drolabel = DROLabel(self.frame)
        self.drolabel.setObjectName(u"drolabel")
        self.drolabel.setGeometry(QRect(80, 10, 291, 61))
        self.drolabel.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Noto Sans\";")
        self.drolabel.setFrameShape(QFrame.NoFrame)
        self.drolabel.setTextFormat(Qt.AutoText)
        self.drolabel.setProperty("Qreference_type", 1)
        self.drolabel_2 = DROLabel(self.frame)
        self.drolabel_2.setObjectName(u"drolabel_2")
        self.drolabel_2.setGeometry(QRect(80, 70, 291, 61))
        self.drolabel_2.setStyleSheet(u"font: 75 48pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.drolabel_2.setProperty("Qjoint_number", 1)
        self.drolabel_2.setProperty("Qreference_type", 1)
        self.drolabel_3 = DROLabel(self.frame)
        self.drolabel_3.setObjectName(u"drolabel_3")
        self.drolabel_3.setGeometry(QRect(80, 130, 291, 61))
        self.drolabel_3.setStyleSheet(u"font: 75 48pt \"Noto Sans\";\n"
"color: rgb(255, 255, 255);")
        self.drolabel_3.setProperty("Qjoint_number", 2)
        self.drolabel_3.setProperty("Qreference_type", 1)
        self.label_18 = QLabel(self.frame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 11, 72, 61))
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Noto Sans\";")
        self.label_19 = QLabel(self.frame)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 70, 72, 61))
        self.label_19.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Noto Sans\";")
        self.label_20 = QLabel(self.frame)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 130, 72, 61))
        self.label_20.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"Noto Sans\";")
        self.state_label_7 = StatusLabel(self.frame)
        self.state_label_7.setObjectName(u"state_label_7")
        self.state_label_7.setGeometry(QRect(280, 190, 131, 31))
        self.state_label_7.setTextFormat(Qt.RichText)
        self.state_label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.state_label_7.setProperty("feed_override_status", False)
        self.state_label_7.setProperty("spindle_override_status", False)
        self.state_label_7.setProperty("current_feedrate_status", True)
        self.StateLabel = StateLabel(self.frame)
        self.StateLabel.setObjectName(u"StateLabel")
        self.StateLabel.setGeometry(QRect(370, 40, 41, 22))
        self.Graphics = GCodeGraphics(self.frame)
        self.Graphics.setObjectName(u"Graphics")
        self.Graphics.setGeometry(QRect(420, 0, 400, 231))
        self.StateLabel_2 = StateLabel(self.frame)
        self.StateLabel_2.setObjectName(u"StateLabel_2")
        self.StateLabel_2.setGeometry(QRect(370, 10, 51, 22))
        self.StateLabel_2.setProperty("metric_mode_status", False)
        self.StateLabel_2.setProperty("diameter_mode_status", True)
        self.state_label_9 = StatusLabel(self.frame)
        self.state_label_9.setObjectName(u"state_label_9")
        self.state_label_9.setGeometry(QRect(100, 190, 91, 31))
        self.state_label_9.setTextFormat(Qt.RichText)
        self.state_label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.state_label_9.setProperty("feed_override_status", False)
        self.state_label_9.setProperty("spindle_override_status", False)
        self.state_label_9.setProperty("current_feedrate_status", False)
        self.state_label_9.setProperty("current_FPU_status", True)
        self.state_label_8 = StatusLabel(self.frame)
        self.state_label_8.setObjectName(u"state_label_8")
        self.state_label_8.setGeometry(QRect(370, 70, 51, 21))
        self.state_label_8.setMidLineWidth(0)
        self.state_label_8.setTextFormat(Qt.RichText)
        self.state_label_8.setProperty("feed_override_status", False)
        self.state_label_8.setProperty("user_system_status", True)
        self.label_22 = QLabel(self.frame)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(200, 190, 101, 31))
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Noto Sans\";")
        self.label_22.setTextFormat(Qt.AutoText)
        self.statelabel_3 = StateLabel(self.frame)
        self.statelabel_3.setObjectName(u"statelabel_3")
        self.statelabel_3.setEnabled(True)
        self.statelabel_3.setGeometry(QRect(10, 191, 81, 31))
        self.statelabel_3.setTextFormat(Qt.AutoText)
        self.gcodeeditor = GcodeEditor(self.centralwidget)
        self.gcodeeditor.setObjectName(u"gcodeeditor")
        self.gcodeeditor.setGeometry(QRect(210, 250, 811, 201))
        self.camviewdialog = CamViewDialog(self.gcodeeditor)
        self.camviewdialog.setObjectName(u"camviewdialog")
        self.camviewdialog.setGeometry(QRect(489, 323, 700, 400))
        self.tooloffsetdialog = ToolOffsetDialog(self.gcodeeditor)
        self.tooloffsetdialog.setObjectName(u"tooloffsetdialog")
        self.tooloffsetdialog.setGeometry(QRect(130, 30, 800, 247))
        self.tooloffsetdialog.setState(False)
        self.state_enable_gridLayout = StateEnableGridLayout(self.centralwidget)
        self.state_enable_gridLayout.setObjectName(u"state_enable_gridLayout")
        self.state_enable_gridLayout.setGeometry(QRect(610, 490, 61, 91))
        self.state_enable_gridLayout.setProperty("is_on_status", True)
        self.state_enable_gridLayout.setProperty("is_idle_status", True)
        self.state_enable_gridLayout.setProperty("is_homed_status", True)
        self.actionbutton = ActionButton(self.state_enable_gridLayout)
        self.actionbutton.setObjectName(u"actionbutton")
        self.actionbutton.setGeometry(QRect(0, 60, 61, 27))
        self.actionbutton.setProperty("estop_action", False)
        self.actionbutton.setProperty("zero_axis_action", True)
        self.actionbutton.setProperty("joint_number", 2)
        self.actionbutton_2 = ActionButton(self.state_enable_gridLayout)
        self.actionbutton_2.setObjectName(u"actionbutton_2")
        self.actionbutton_2.setGeometry(QRect(0, 30, 61, 27))
        self.actionbutton_2.setProperty("estop_action", False)
        self.actionbutton_2.setProperty("zero_axis_action", True)
        self.actionbutton_2.setProperty("joint_number", 1)
        self.actionbutton_3 = ActionButton(self.state_enable_gridLayout)
        self.actionbutton_3.setObjectName(u"actionbutton_3")
        self.actionbutton_3.setGeometry(QRect(0, 0, 61, 27))
        self.actionbutton_3.setProperty("estop_action", False)
        self.actionbutton_3.setProperty("zero_axis_action", True)
        self.actionbutton_3.setProperty("joint_number", 0)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 650, 72, 22))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 650, 61, 22))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(700, 500, 71, 22))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(700, 530, 72, 22))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(360, 580, 301, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.state_label = StatusLabel(self.centralwidget)
        self.state_label.setObjectName(u"state_label")
        self.state_label.setGeometry(QRect(130, 685, 101, 31))
        self.state_label.setTextFormat(Qt.RichText)
        self.state_label.setProperty("feed_override_status", False)
        self.state_label.setProperty("rapid_override_status", True)
        self.state_label_2 = StatusLabel(self.centralwidget)
        self.state_label_2.setObjectName(u"state_label_2")
        self.state_label_2.setGeometry(QRect(20, 685, 101, 31))
        self.state_label_2.setTextFormat(Qt.RichText)
        self.state_label_3 = StatusLabel(self.centralwidget)
        self.state_label_3.setObjectName(u"state_label_3")
        self.state_label_3.setGeometry(QRect(240, 685, 101, 31))
        self.state_label_3.setTextFormat(Qt.RichText)
        self.state_label_3.setProperty("feed_override_status", False)
        self.state_label_3.setProperty("spindle_override_status", True)
        self.state_label_4 = StatusLabel(self.centralwidget)
        self.state_label_4.setObjectName(u"state_label_4")
        self.state_label_4.setGeometry(QRect(760, 490, 71, 41))
        self.state_label_4.setTextFormat(Qt.RichText)
        self.state_label_4.setProperty("feed_override_status", False)
        self.state_label_4.setProperty("spindle_override_status", False)
        self.state_label_4.setProperty("tool_number_status", True)
        self.state_label_5 = StatusLabel(self.centralwidget)
        self.state_label_5.setObjectName(u"state_label_5")
        self.state_label_5.setGeometry(QRect(90, 640, 61, 41))
        self.state_label_5.setTextFormat(Qt.RichText)
        self.state_label_5.setProperty("feed_override_status", False)
        self.state_label_5.setProperty("spindle_override_status", False)
        self.state_label_5.setProperty("jograte_status", True)
        self.state_label_5.setProperty("tool_number_status", False)
        self.state_label_6 = StatusLabel(self.centralwidget)
        self.state_label_6.setObjectName(u"state_label_6")
        self.state_label_6.setGeometry(QRect(410, 610, 251, 61))
        self.state_label_6.setTextFormat(Qt.RichText)
        self.state_label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.state_label_6.setProperty("feed_override_status", False)
        self.state_label_6.setProperty("spindle_override_status", False)
        self.state_label_6.setProperty("requested_spindle_speed_status", False)
        self.state_label_6.setProperty("actual_spindle_speed_status", True)
        self.tooldialog = ToolDialog(self.centralwidget)
        self.tooldialog.setObjectName(u"tooldialog")
        self.tooldialog.setGeometry(QRect(480, 760, 316, 121))
        self.tooldialog.setState(False)
        self.focusoverlay = FocusOverlay(self.centralwidget)
        self.focusoverlay.setObjectName(u"focusoverlay")
        self.focusoverlay.setGeometry(QRect(0, 0, 1027, 847))
        self.focusoverlay.setState(False)
        self.focusoverlay.setProperty("show_image_option", True)
        self.lcncdialog = LcncDialog(self.centralwidget)
        self.lcncdialog.setObjectName(u"lcncdialog")
        self.lcncdialog.setGeometry(QRect(340, 770, 336, 104))
        self.lcncdialog.setState(False)
        self.filedialog = FileDialog(self.centralwidget)
        self.filedialog.setObjectName(u"filedialog")
        self.filedialog.setGeometry(QRect(390, 240, 635, 448))
        self.filedialog.setState(False)
        self.filedialog.setProperty("color", QColor(0, 0, 255, 150))
        self.led_home_x = StateLED(self.centralwidget)
        self.led_home_x.setObjectName(u"led_home_x")
        self.led_home_x.setGeometry(QRect(590, 490, 21, 21))
        self.led_home_x.setDiameter(10)
        self.led_home_x.setColor(QColor(255, 255, 0, 214))
        self.led_home_x.setProperty("flashing", True)
        self.led_home_x.setFlashRate(600)
        self.led_home_x.setProperty("invert_state_status", True)
        self.led_home_x.setProperty("is_joint_homed_status", True)
        self.led_home_y = StateLED(self.centralwidget)
        self.led_home_y.setObjectName(u"led_home_y")
        self.led_home_y.setGeometry(QRect(590, 520, 21, 21))
        self.led_home_y.setDiameter(10)
        self.led_home_y.setColor(QColor(255, 255, 0, 214))
        self.led_home_y.setProperty("flashing", True)
        self.led_home_y.setFlashRate(600)
        self.led_home_y.setProperty("invert_state_status", True)
        self.led_home_y.setProperty("is_joint_homed_status", True)
        self.led_home_y.setProperty("joint_number_status", 1)
        self.led_home_z = StateLED(self.centralwidget)
        self.led_home_z.setObjectName(u"led_home_z")
        self.led_home_z.setGeometry(QRect(590, 550, 21, 21))
        self.led_home_z.setDiameter(10)
        self.led_home_z.setColor(QColor(255, 255, 0, 214))
        self.led_home_z.setProperty("flashing", True)
        self.led_home_z.setFlashRate(600)
        self.led_home_z.setProperty("invert_state_status", True)
        self.led_home_z.setProperty("is_joint_homed_status", True)
        self.led_home_z.setProperty("joint_number_status", 2)
        self.actionbutton_9 = ActionButton(self.centralwidget)
        self.actionbutton_9.setObjectName(u"actionbutton_9")
        self.actionbutton_9.setGeometry(QRect(360, 685, 56, 31))
        self.actionbutton_9.setCheckable(True)
        self.actionbutton_9.setAutoExclusive(True)
        self.actionbutton_9.setProperty("indicator_option", True)
        self.actionbutton_9.setProperty("HAL_pin_option", False)
        self.actionbutton_9.setProperty("manual_action", True)
        self.actionbutton_10 = ActionButton(self.centralwidget)
        self.actionbutton_10.setObjectName(u"actionbutton_10")
        self.actionbutton_10.setGeometry(QRect(490, 685, 56, 31))
        self.actionbutton_10.setCheckable(True)
        self.actionbutton_10.setAutoExclusive(True)
        self.actionbutton_10.setProperty("indicator_option", True)
        self.actionbutton_10.setProperty("HAL_pin_option", False)
        self.actionbutton_10.setProperty("mdi_action", True)
        self.actionbutton_10.setProperty("manual_action", False)
        self.actionbutton_11 = ActionButton(self.centralwidget)
        self.actionbutton_11.setObjectName(u"actionbutton_11")
        self.actionbutton_11.setGeometry(QRect(610, 685, 56, 31))
        self.actionbutton_11.setCheckable(True)
        self.actionbutton_11.setAutoExclusive(True)
        self.actionbutton_11.setProperty("indicator_option", True)
        self.actionbutton_11.setProperty("HAL_pin_option", False)
        self.actionbutton_11.setProperty("auto_action", True)
        self.actionbutton_11.setProperty("manual_action", False)
        self.ScreenOptions = ScreenOptions(self.centralwidget)
        self.ScreenOptions.setObjectName(u"ScreenOptions")
        self.ScreenOptions.setGeometry(QRect(240, 820, 16, 16))
        self.StatusLabel_2 = StatusLabel(self.centralwidget)
        self.StatusLabel_2.setObjectName(u"StatusLabel_2")
        self.StatusLabel_2.setGeometry(QRect(210, 640, 131, 41))
        self.StatusLabel_2.setProperty("jogincr_status", True)
        self.macrotabdialog = MacroTabDialog(self.centralwidget)
        self.macrotabdialog.setObjectName(u"macrotabdialog")
        self.macrotabdialog.setGeometry(QRect(390, 230, 600, 400))
        self.macrotabdialog.setState(False)
        self.originoffsetdialog = OriginOffsetDialog(self.centralwidget)
        self.originoffsetdialog.setObjectName(u"originoffsetdialog")
        self.originoffsetdialog.setGeometry(QRect(40, 40, 800, 500))
        self.originoffsetdialog.setState(False)
        self.StatusStacked = StatusStacked(self.centralwidget)
        self.StatusStacked.setObjectName(u"StatusStacked")
        self.StatusStacked.setGeometry(QRect(10, 10, 191, 441))
        self.StatusStacked.setStyleSheet(u"")
        self.page_man = QWidget()
        self.page_man.setObjectName(u"page_man")
        self.frame_man = QFrame(self.page_man)
        self.frame_man.setObjectName(u"frame_man")
        self.frame_man.setGeometry(QRect(0, 0, 191, 441))
        self.frame_man.setStyleSheet(u"")
        self.frame_man.setFrameShape(QFrame.StyledPanel)
        self.frame_man.setFrameShadow(QFrame.Raised)
        self.state_enable_gridLayout_5 = StateEnableGridLayout(self.frame_man)
        self.state_enable_gridLayout_5.setObjectName(u"state_enable_gridLayout_5")
        self.state_enable_gridLayout_5.setEnabled(False)
        self.state_enable_gridLayout_5.setGeometry(QRect(0, 260, 191, 181))
        self.state_enable_gridLayout_5.setStyleSheet(u"")
        self.state_enable_gridLayout_5.setProperty("is_on_status", True)
        self.state_enable_gridLayout_5.setProperty("is_idle_status", True)
        self.frame_3 = QFrame(self.state_enable_gridLayout_5)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 9, 191, 171))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.jog_pos_x = ActionButton(self.frame_3)
        self.jog_pos_x.setObjectName(u"jog_pos_x")
        self.jog_pos_x.setGeometry(QRect(130, 70, 56, 32))
        self.jog_pos_x.setProperty("estop_action", False)
        self.jog_pos_x.setProperty("jog_joint_pos_action", True)
        self.jog_neg_x = ActionButton(self.frame_3)
        self.jog_neg_x.setObjectName(u"jog_neg_x")
        self.jog_neg_x.setGeometry(QRect(10, 70, 56, 32))
        self.jog_neg_x.setProperty("estop_action", False)
        self.jog_neg_x.setProperty("jog_joint_neg_action", True)
        self.jog_pos_z = ActionButton(self.frame_3)
        self.jog_pos_z.setObjectName(u"jog_pos_z")
        self.jog_pos_z.setGeometry(QRect(130, 0, 56, 32))
        self.jog_pos_z.setProperty("estop_action", False)
        self.jog_pos_z.setProperty("jog_joint_pos_action", True)
        self.jog_pos_z.setProperty("joint_number", 2)
        self.jog_pos_z.setProperty("jog_joint_number", 2)
        self.jog_neg_z = ActionButton(self.frame_3)
        self.jog_neg_z.setObjectName(u"jog_neg_z")
        self.jog_neg_z.setGeometry(QRect(10, 140, 56, 32))
        self.jog_neg_z.setProperty("estop_action", False)
        self.jog_neg_z.setProperty("jog_joint_pos_action", False)
        self.jog_neg_z.setProperty("jog_joint_neg_action", True)
        self.jog_neg_z.setProperty("joint_number", 2)
        self.jog_neg_z.setProperty("jog_joint_number", 2)
        self.jog_neg_y = ActionButton(self.frame_3)
        self.jog_neg_y.setObjectName(u"jog_neg_y")
        self.jog_neg_y.setGeometry(QRect(70, 110, 56, 32))
        self.jog_neg_y.setProperty("estop_action", False)
        self.jog_neg_y.setProperty("jog_joint_pos_action", False)
        self.jog_neg_y.setProperty("jog_joint_neg_action", True)
        self.jog_neg_y.setProperty("joint_number", 1)
        self.jog_neg_y.setProperty("jog_joint_number", 1)
        self.jog_pos_y = ActionButton(self.frame_3)
        self.jog_pos_y.setObjectName(u"jog_pos_y")
        self.jog_pos_y.setGeometry(QRect(70, 30, 56, 32))
        self.jog_pos_y.setProperty("estop_action", False)
        self.jog_pos_y.setProperty("jog_joint_pos_action", True)
        self.jog_pos_y.setProperty("joint_number", 1)
        self.jog_pos_y.setProperty("jog_joint_number", 1)
        self.JogIncrements = JogIncrements(self.frame_3)
        self.JogIncrements.setObjectName(u"JogIncrements")
        self.JogIncrements.setGeometry(QRect(80, 150, 101, 21))
        self.button_home = ActionButton(self.frame_man)
        self.button_home.setObjectName(u"button_home")
        self.button_home.setGeometry(QRect(30, 10, 131, 41))
        self.button_home.setStyleSheet(u"font: 75 italic 20pt \"Noto Sans\";")
        self.button_home.setCheckable(True)
        self.button_home.setProperty("estop_action", False)
        self.button_home.setProperty("home_action", True)
        self.button_home.setProperty("joint_number", -1)
        self.actionbutton_25 = ActionButton(self.frame_man)
        self.actionbutton_25.setObjectName(u"actionbutton_25")
        self.actionbutton_25.setGeometry(QRect(130, 150, 55, 32))
        self.actionbutton_25.setProperty("spindle_fwd_action", True)
        self.actionbutton_25.setProperty("spindle_rev_action", False)
        self.actionbutton_25.setProperty("spindle_stop_action", False)
        self.actionbutton_25.setProperty("spindle_up_action", False)
        self.actionbutton_25.setProperty("spindle_down_action", False)
        self.actionbutton_25.setProperty("view_change_action", False)
        self.actionbutton_26 = ActionButton(self.frame_man)
        self.actionbutton_26.setObjectName(u"actionbutton_26")
        self.actionbutton_26.setGeometry(QRect(10, 150, 55, 32))
        self.actionbutton_26.setProperty("spindle_rev_action", True)
        self.actionbutton_26.setProperty("spindle_down_action", False)
        self.actionbutton_27 = ActionButton(self.frame_man)
        self.actionbutton_27.setObjectName(u"actionbutton_27")
        self.actionbutton_27.setGeometry(QRect(130, 190, 55, 32))
        self.actionbutton_27.setProperty("spindle_up_action", True)
        self.actionbutton_28 = ActionButton(self.frame_man)
        self.actionbutton_28.setObjectName(u"actionbutton_28")
        self.actionbutton_28.setGeometry(QRect(10, 190, 55, 32))
        self.actionbutton_28.setProperty("spindle_down_action", True)
        self.actionbutton_29 = ActionButton(self.frame_man)
        self.actionbutton_29.setObjectName(u"actionbutton_29")
        self.actionbutton_29.setGeometry(QRect(70, 161, 55, 51))
        self.actionbutton_29.setProperty("spindle_stop_action", True)
        self.actionbutton_14 = ActionButton(self.frame_man)
        self.actionbutton_14.setObjectName(u"actionbutton_14")
        self.actionbutton_14.setGeometry(QRect(10, 70, 81, 41))
        self.actionbutton_14.setProperty("origin_offset_dialog_action", True)
        self.actionbutton_14.setProperty("macro_dialog_action", False)
        self.actionbutton_13 = ActionButton(self.frame_man)
        self.actionbutton_13.setObjectName(u"actionbutton_13")
        self.actionbutton_13.setGeometry(QRect(100, 70, 81, 41))
        self.actionbutton_13.setProperty("camview_dialog_action", True)
        self.actionbutton_13.setProperty("macro_dialog_action", False)
        self.StateLED_3 = StateLED(self.frame_man)
        self.StateLED_3.setObjectName(u"StateLED_3")
        self.StateLED_3.setGeometry(QRect(140, 10, 20, 20))
        self.StateLED_3.setDiameter(10)
        self.StateLED_3.setColor(QColor(255, 255, 0, 214))
        self.StateLED_3.setProperty("flashing", True)
        self.StateLED_3.setProperty("invert_state_status", True)
        self.StateLED_3.setProperty("is_homed_status", True)
        self.StatusStacked.addWidget(self.page_man)
        self.page_mdi = QWidget()
        self.page_mdi.setObjectName(u"page_mdi")
        self.frame_mdi = QFrame(self.page_mdi)
        self.frame_mdi.setObjectName(u"frame_mdi")
        self.frame_mdi.setGeometry(QRect(0, 0, 191, 441))
        self.frame_mdi.setStyleSheet(u"")
        self.frame_mdi.setFrameShape(QFrame.StyledPanel)
        self.frame_mdi.setFrameShadow(QFrame.Raised)
        self.actionbutton_12 = ActionButton(self.frame_mdi)
        self.actionbutton_12.setObjectName(u"actionbutton_12")
        self.actionbutton_12.setGeometry(QRect(50, 80, 91, 41))
        self.actionbutton_12.setProperty("macro_dialog_action", True)
        self.actionbutton_32 = ActionButton(self.frame_mdi)
        self.actionbutton_32.setObjectName(u"actionbutton_32")
        self.actionbutton_32.setGeometry(QRect(50, 180, 91, 41))
        self.actionbutton_32.setProperty("mdi_command_action", True)
        self.actionbutton_33 = ActionButton(self.frame_mdi)
        self.actionbutton_33.setObjectName(u"actionbutton_33")
        self.actionbutton_33.setGeometry(QRect(50, 230, 91, 41))
        self.actionbutton_33.setProperty("mdi_command_action", True)
        self.StatusStacked.addWidget(self.page_mdi)
        self.page_auto = QWidget()
        self.page_auto.setObjectName(u"page_auto")
        self.frame_auto = QFrame(self.page_auto)
        self.frame_auto.setObjectName(u"frame_auto")
        self.frame_auto.setGeometry(QRect(0, 0, 191, 441))
        self.frame_auto.setStyleSheet(u"")
        self.frame_auto.setFrameShape(QFrame.StyledPanel)
        self.frame_auto.setFrameShadow(QFrame.Raised)
        self.actionbutton_load = ActionButton(self.frame_auto)
        self.actionbutton_load.setObjectName(u"actionbutton_load")
        self.actionbutton_load.setGeometry(QRect(20, 60, 61, 61))
        self.actionbutton_load.setProperty("estop_action", False)
        self.actionbutton_load.setProperty("load_dialog_action", True)
        self.actionbutton_4 = ActionButton(self.frame_auto)
        self.actionbutton_4.setObjectName(u"actionbutton_4")
        self.actionbutton_4.setGeometry(QRect(100, 60, 61, 61))
        self.actionbutton_4.setProperty("estop_action", False)
        self.actionbutton_4.setProperty("run_action", True)
        self.actionbutton_19 = ActionButton(self.frame_auto)
        self.actionbutton_19.setObjectName(u"actionbutton_19")
        self.actionbutton_19.setGeometry(QRect(30, 190, 61, 32))
        self.actionbutton_19.setProperty("view_change_action", True)
        self.actionbutton_20 = ActionButton(self.frame_auto)
        self.actionbutton_20.setObjectName(u"actionbutton_20")
        self.actionbutton_20.setGeometry(QRect(100, 190, 61, 32))
        self.actionbutton_20.setProperty("view_change_action", True)
        self.actionbutton_21 = ActionButton(self.frame_auto)
        self.actionbutton_21.setObjectName(u"actionbutton_21")
        self.actionbutton_21.setGeometry(QRect(30, 240, 61, 32))
        self.actionbutton_21.setProperty("view_change_action", True)
        self.actionbutton_22 = ActionButton(self.frame_auto)
        self.actionbutton_22.setObjectName(u"actionbutton_22")
        self.actionbutton_22.setGeometry(QRect(100, 240, 61, 32))
        self.actionbutton_22.setProperty("view_change_action", True)
        self.actionbutton_23 = ActionButton(self.frame_auto)
        self.actionbutton_23.setObjectName(u"actionbutton_23")
        self.actionbutton_23.setGeometry(QRect(20, 290, 71, 32))
        self.actionbutton_23.setProperty("view_change_action", True)
        self.actionbutton_24 = ActionButton(self.frame_auto)
        self.actionbutton_24.setObjectName(u"actionbutton_24")
        self.actionbutton_24.setGeometry(QRect(100, 290, 71, 32))
        self.actionbutton_24.setProperty("view_change_action", True)
        self.StatusStacked.addWidget(self.page_auto)
        self.StatusSlider = StatusSlider(self.centralwidget)
        self.StatusSlider.setObjectName(u"StatusSlider")
        self.StatusSlider.setGeometry(QRect(860, 550, 91, 21))
        self.StatusSlider.setMaximum(100)
        self.StatusSlider.setOrientation(Qt.Horizontal)
        self.StatusSlider.setTickPosition(QSlider.NoTicks)
        self.StatusSlider.setTickInterval(10)
        self.StatusSlider_2 = StatusSlider(self.centralwidget)
        self.StatusSlider_2.setObjectName(u"StatusSlider_2")
        self.StatusSlider_2.setGeometry(QRect(860, 580, 91, 21))
        self.StatusSlider_2.setMaximum(200)
        self.StatusSlider_2.setOrientation(Qt.Horizontal)
        self.StatusSlider_2.setTickPosition(QSlider.NoTicks)
        self.StatusSlider_2.setTickInterval(10)
        self.StatusSlider_2.setProperty("rapid_rate", False)
        self.StatusSlider_2.setProperty("feed_rate", True)
        self.StatusSlider_6 = StatusSlider(self.centralwidget)
        self.StatusSlider_6.setObjectName(u"StatusSlider_6")
        self.StatusSlider_6.setGeometry(QRect(860, 610, 91, 21))
        self.StatusSlider_6.setMinimum(50)
        self.StatusSlider_6.setMaximum(150)
        self.StatusSlider_6.setOrientation(Qt.Horizontal)
        self.StatusSlider_6.setTickPosition(QSlider.NoTicks)
        self.StatusSlider_6.setTickInterval(10)
        self.StatusSlider_6.setProperty("rapid_rate", False)
        self.StatusSlider_6.setProperty("spindle_rate", True)
        self.StatusSlider_5 = StatusSlider(self.centralwidget)
        self.StatusSlider_5.setObjectName(u"StatusSlider_5")
        self.StatusSlider_5.setGeometry(QRect(860, 640, 91, 21))
        self.StatusSlider_5.setMaximum(100)
        self.StatusSlider_5.setOrientation(Qt.Horizontal)
        self.StatusSlider_5.setTickPosition(QSlider.NoTicks)
        self.StatusSlider_5.setTickInterval(10)
        self.StatusSlider_5.setProperty("rapid_rate", False)
        self.StatusSlider_5.setProperty("jograte_rate", True)
        self.mcodes_label = StatusLabel(self.centralwidget)
        self.mcodes_label.setObjectName(u"mcodes_label")
        self.mcodes_label.setGeometry(QRect(20, 725, 311, 31))
        self.mcodes_label.setTextFormat(Qt.RichText)
        self.mcodes_label.setProperty("gcodes_status", False)
        self.mcodes_label.setProperty("mcodes_status", True)
        self.actionbutton_15 = ActionButton(self.centralwidget)
        self.actionbutton_15.setObjectName(u"actionbutton_15")
        self.actionbutton_15.setGeometry(QRect(955, 580, 51, 24))
        self.actionbutton_15.setProperty("feed_over_action", True)
        self.actionbutton_15.setProperty("toggle_float_option", True)
        self.actionbutton_15.setProperty("float_alt_num", 75.000000000000000)
        self.actionbutton_16 = ActionButton(self.centralwidget)
        self.actionbutton_16.setObjectName(u"actionbutton_16")
        self.actionbutton_16.setGeometry(QRect(955, 550, 51, 24))
        self.actionbutton_16.setProperty("feed_over_action", False)
        self.actionbutton_16.setProperty("rapid_over_action", True)
        self.actionbutton_16.setProperty("toggle_float_option", True)
        self.actionbutton_16.setProperty("float_alt_num", 25.000000000000000)
        self.actionbutton_17 = ActionButton(self.centralwidget)
        self.actionbutton_17.setObjectName(u"actionbutton_17")
        self.actionbutton_17.setGeometry(QRect(955, 610, 51, 24))
        self.actionbutton_17.setProperty("feed_over_action", False)
        self.actionbutton_17.setProperty("rapid_over_action", False)
        self.actionbutton_17.setProperty("spindle_over_action", True)
        self.actionbutton_17.setProperty("toggle_float_option", True)
        self.actionbutton_17.setProperty("float_alt_num", 90.000000000000000)
        self.actionbutton_18 = ActionButton(self.centralwidget)
        self.actionbutton_18.setObjectName(u"actionbutton_18")
        self.actionbutton_18.setGeometry(QRect(955, 640, 51, 24))
        self.actionbutton_18.setProperty("jog_rate_action", True)
        self.actionbutton_18.setProperty("feed_over_action", False)
        self.actionbutton_18.setProperty("rapid_over_action", False)
        self.actionbutton_18.setProperty("spindle_over_action", False)
        self.actionbutton_18.setProperty("toggle_float_option", True)
        self.actionbutton_18.setProperty("float_num", 60.000000000000000)
        self.actionbutton_18.setProperty("float_alt_num", 15.000000000000000)
        self.frame_auto_2 = QFrame(self.centralwidget)
        self.frame_auto_2.setObjectName(u"frame_auto_2")
        self.frame_auto_2.setGeometry(QRect(10, 460, 341, 221))
        self.frame_auto_2.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_2.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_2.setFrameShadow(QFrame.Raised)
        self.actionbutton_override_limits = ActionButton(self.frame_auto_2)
        self.actionbutton_override_limits.setObjectName(u"actionbutton_override_limits")
        self.actionbutton_override_limits.setGeometry(QRect(130, 10, 121, 27))
        self.actionbutton_override_limits.setProperty("limits_override_action", True)
        self.StateLED_9 = StateLED(self.frame_auto_2)
        self.StateLED_9.setObjectName(u"StateLED_9")
        self.StateLED_9.setGeometry(QRect(230, 0, 31, 41))
        self.StateLED_9.setDiameter(10)
        self.StateLED_9.setProperty("flashing", False)
        self.StateLED_9.setProperty("is_paused_status", False)
        self.StateLED_9.setProperty("is_flood_status", False)
        self.StateLED_9.setProperty("is_block_delete_status", False)
        self.StateLED_9.setProperty("is_limits_overridden_status", True)
        self.StateLED_9.setProperty("is_limits_overriden_status", True)
        self.button_estop = ActionButton(self.frame_auto_2)
        self.button_estop.setObjectName(u"button_estop")
        self.button_estop.setGeometry(QRect(10, 10, 101, 41))
        self.button_estop.setStyleSheet(u"font: 75 italic 20pt \"Noto Sans\";")
        self.button_estop.setCheckable(True)
        self.button_estop.setChecked(False)
        self.button_estop.setProperty("estop_action", True)
        self.button_machineon = ActionButton(self.frame_auto_2)
        self.button_machineon.setObjectName(u"button_machineon")
        self.button_machineon.setGeometry(QRect(10, 60, 101, 41))
        self.button_machineon.setStyleSheet(u"font: 75 italic 20pt \"Noto Sans\";")
        self.button_machineon.setCheckable(True)
        self.button_machineon.setProperty("estop_action", False)
        self.button_machineon.setProperty("machine_on_action", True)
        self.actionbutton_flood = ActionButton(self.frame_auto_2)
        self.actionbutton_flood.setObjectName(u"actionbutton_flood")
        self.actionbutton_flood.setGeometry(QRect(130, 100, 121, 27))
        self.actionbutton_flood.setCheckable(False)
        self.actionbutton_flood.setProperty("limits_override_action", False)
        self.actionbutton_flood.setProperty("flood_action", True)
        self.actionbutton_mist = ActionButton(self.frame_auto_2)
        self.actionbutton_mist.setObjectName(u"actionbutton_mist")
        self.actionbutton_mist.setGeometry(QRect(130, 130, 121, 27))
        self.actionbutton_mist.setCheckable(False)
        self.actionbutton_mist.setProperty("limits_override_action", False)
        self.actionbutton_mist.setProperty("mist_action", True)
        self.actionbutton_block_delete = ActionButton(self.frame_auto_2)
        self.actionbutton_block_delete.setObjectName(u"actionbutton_block_delete")
        self.actionbutton_block_delete.setGeometry(QRect(130, 40, 121, 27))
        self.actionbutton_block_delete.setCheckable(False)
        self.actionbutton_block_delete.setProperty("limits_override_action", False)
        self.actionbutton_block_delete.setProperty("block_delete_action", True)
        self.actionbutton_optional_stop = ActionButton(self.frame_auto_2)
        self.actionbutton_optional_stop.setObjectName(u"actionbutton_optional_stop")
        self.actionbutton_optional_stop.setGeometry(QRect(130, 70, 121, 27))
        self.actionbutton_optional_stop.setCheckable(False)
        self.actionbutton_optional_stop.setProperty("limits_override_action", False)
        self.actionbutton_optional_stop.setProperty("block_delete_action", False)
        self.actionbutton_optional_stop.setProperty("optional_stop_action", True)
        self.StateLED_8 = StateLED(self.frame_auto_2)
        self.StateLED_8.setObjectName(u"StateLED_8")
        self.StateLED_8.setGeometry(QRect(230, 30, 31, 41))
        self.StateLED_8.setDiameter(10)
        self.StateLED_8.setColor(QColor(85, 255, 0))
        self.StateLED_8.setProperty("flashing", False)
        self.StateLED_8.setProperty("is_paused_status", False)
        self.StateLED_8.setProperty("is_flood_status", False)
        self.StateLED_8.setProperty("is_block_delete_status", True)
        self.StateLED_7 = StateLED(self.frame_auto_2)
        self.StateLED_7.setObjectName(u"StateLED_7")
        self.StateLED_7.setGeometry(QRect(230, 60, 31, 41))
        self.StateLED_7.setDiameter(10)
        self.StateLED_7.setColor(QColor(85, 255, 0))
        self.StateLED_7.setState(False)
        self.StateLED_7.setProperty("flashing", False)
        self.StateLED_7.setProperty("invert_state_status", False)
        self.StateLED_7.setProperty("is_paused_status", False)
        self.StateLED_7.setProperty("is_flood_status", False)
        self.StateLED_7.setProperty("is_optional_stop_status", True)
        self.StateLED_5 = StateLED(self.frame_auto_2)
        self.StateLED_5.setObjectName(u"StateLED_5")
        self.StateLED_5.setGeometry(QRect(230, 100, 31, 21))
        self.StateLED_5.setDiameter(10)
        self.StateLED_5.setColor(QColor(85, 255, 0))
        self.StateLED_5.setProperty("flashing", False)
        self.StateLED_5.setProperty("is_paused_status", False)
        self.StateLED_5.setProperty("is_flood_status", True)
        self.StateLED_6 = StateLED(self.frame_auto_2)
        self.StateLED_6.setObjectName(u"StateLED_6")
        self.StateLED_6.setGeometry(QRect(230, 130, 31, 21))
        self.StateLED_6.setDiameter(10)
        self.StateLED_6.setColor(QColor(85, 255, 0))
        self.StateLED_6.setProperty("flashing", False)
        self.StateLED_6.setProperty("is_paused_status", False)
        self.StateLED_6.setProperty("is_mist_status", True)
        self.led_machine_on = StateLED(self.frame_auto_2)
        self.led_machine_on.setObjectName(u"led_machine_on")
        self.led_machine_on.setGeometry(QRect(90, 60, 31, 21))
        self.led_machine_on.setDiameter(15)
        self.led_machine_on.setColor(QColor(85, 255, 0))
        self.led_machine_on.setProperty("flashing", False)
        self.led_machine_on.setProperty("is_on_status", True)
        self.led_machine_on.setProperty("is_idle_status", False)
        self.StateLED = StateLED(self.frame_auto_2)
        self.StateLED.setObjectName(u"StateLED")
        self.StateLED.setGeometry(QRect(90, 10, 21, 21))
        self.StateLED.setDiameter(20)
        self.StateLED.setProperty("flashing", True)
        self.StateLED.setProperty("is_estopped_status", True)
        self.actionbutton_6 = ActionButton(self.frame_auto_2)
        self.actionbutton_6.setObjectName(u"actionbutton_6")
        self.actionbutton_6.setGeometry(QRect(10, 110, 101, 51))
        self.actionbutton_6.setProperty("estop_action", False)
        self.actionbutton_6.setProperty("abort_action", True)
        self.actionbutton_6.setProperty("pause_action", False)
        self.actionbutton_5 = ActionButton(self.frame_auto_2)
        self.actionbutton_5.setObjectName(u"actionbutton_5")
        self.actionbutton_5.setGeometry(QRect(260, 10, 61, 61))
        self.actionbutton_5.setProperty("estop_action", False)
        self.actionbutton_5.setProperty("abort_action", False)
        self.actionbutton_5.setProperty("pause_action", True)
        self.StateLED_4 = StateLED(self.frame_auto_2)
        self.StateLED_4.setObjectName(u"StateLED_4")
        self.StateLED_4.setGeometry(QRect(300, 10, 31, 16))
        self.StateLED_4.setDiameter(10)
        self.StateLED_4.setProperty("flashing", True)
        self.StateLED_4.setProperty("is_paused_status", True)
        self.frame_auto_3 = QFrame(self.centralwidget)
        self.frame_auto_3.setObjectName(u"frame_auto_3")
        self.frame_auto_3.setGeometry(QRect(350, 460, 331, 221))
        self.frame_auto_3.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_3.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_3.setFrameShadow(QFrame.Raised)
        self.frame_auto_4 = QFrame(self.centralwidget)
        self.frame_auto_4.setObjectName(u"frame_auto_4")
        self.frame_auto_4.setGeometry(QRect(850, 460, 171, 221))
        self.frame_auto_4.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_4.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_4.setFrameShadow(QFrame.Raised)
        self.actionbutton_7 = ActionButton(self.frame_auto_4)
        self.actionbutton_7.setObjectName(u"actionbutton_7")
        self.actionbutton_7.setGeometry(QRect(10, 10, 45, 27))
        self.actionbutton_7.setProperty("indicator_option", True)
        self.actionbutton_7.setProperty("HAL_pin_option", False)
        self.actionbutton_7.setProperty("jog_incr_action", True)
        self.actionbutton_7.setProperty("incr_imperial_number", 0.001000000000000)
        self.actionbutton_7.setProperty("incr_mm_number", 0.010000000000000)
        self.actionbutton_8 = ActionButton(self.frame_auto_4)
        self.actionbutton_8.setObjectName(u"actionbutton_8")
        self.actionbutton_8.setGeometry(QRect(60, 10, 45, 27))
        self.actionbutton_8.setProperty("indicator_option", True)
        self.actionbutton_8.setProperty("HAL_pin_option", False)
        self.actionbutton_8.setProperty("jog_incr_action", True)
        self.actionbutton_8.setProperty("incr_imperial_number", 0.010000000000000)
        self.actionbutton_8.setProperty("incr_mm_number", 0.100000000000000)
        self.actionbutton_30 = ActionButton(self.frame_auto_4)
        self.actionbutton_30.setObjectName(u"actionbutton_30")
        self.actionbutton_30.setGeometry(QRect(110, 10, 45, 27))
        self.actionbutton_30.setProperty("indicator_option", True)
        self.actionbutton_30.setProperty("HAL_pin_option", False)
        self.actionbutton_30.setProperty("jog_incr_action", True)
        self.actionbutton_30.setProperty("incr_imperial_number", 0.100000000000000)
        self.actionbutton_30.setProperty("incr_mm_number", 1.000000000000000)
        self.actionbutton_31 = ActionButton(self.frame_auto_4)
        self.actionbutton_31.setObjectName(u"actionbutton_31")
        self.actionbutton_31.setGeometry(QRect(20, 40, 121, 27))
        self.actionbutton_31.setProperty("indicator_option", True)
        self.actionbutton_31.setProperty("HAL_pin_option", False)
        self.actionbutton_31.setProperty("jog_incr_action", True)
        self.actionbutton_31.setProperty("incr_imperial_number", 0.000000000000000)
        self.actionbutton_31.setProperty("incr_mm_number", 0.000000000000000)
        self.frame_auto_6 = QFrame(self.centralwidget)
        self.frame_auto_6.setObjectName(u"frame_auto_6")
        self.frame_auto_6.setGeometry(QRect(10, 680, 341, 41))
        self.frame_auto_6.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_6.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_6.setFrameShadow(QFrame.Raised)
        self.frame_auto_7 = QFrame(self.centralwidget)
        self.frame_auto_7.setObjectName(u"frame_auto_7")
        self.frame_auto_7.setGeometry(QRect(350, 680, 331, 41))
        self.frame_auto_7.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_7.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_7.setFrameShadow(QFrame.Raised)
        self.frame_auto_9 = QFrame(self.centralwidget)
        self.frame_auto_9.setObjectName(u"frame_auto_9")
        self.frame_auto_9.setGeometry(QRect(10, 720, 341, 41))
        self.frame_auto_9.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_9.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_9.setFrameShadow(QFrame.Raised)
        self.frame_auto_10 = QFrame(self.centralwidget)
        self.frame_auto_10.setObjectName(u"frame_auto_10")
        self.frame_auto_10.setGeometry(QRect(350, 720, 671, 41))
        self.frame_auto_10.setStyleSheet(u"")
        self.frame_auto_10.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_10.setFrameShadow(QFrame.Raised)
        self.frame_auto_8 = QFrame(self.centralwidget)
        self.frame_auto_8.setObjectName(u"frame_auto_8")
        self.frame_auto_8.setGeometry(QRect(680, 680, 341, 41))
        self.frame_auto_8.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_8.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_8.setFrameShadow(QFrame.Raised)
        self.mdi_line = MDILine(self.frame_auto_8)
        self.mdi_line.setObjectName(u"mdi_line")
        self.mdi_line.setGeometry(QRect(60, -4, 271, 41))
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.mdi_line.setFont(font)
        self.mdi_line.setProperty("soft_keyboard_option", True)
        self.label_11 = QLabel(self.frame_auto_8)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 0, 61, 41))
        self.gcodes_label = StatusLabel(self.centralwidget)
        self.gcodes_label.setObjectName(u"gcodes_label")
        self.gcodes_label.setGeometry(QRect(370, 725, 651, 31))
        self.gcodes_label.setTextFormat(Qt.RichText)
        self.gcodes_label.setProperty("gcodes_status", True)
        self.gcodes_label.setProperty("mcodes_status", False)
        self.frame_auto_5 = QFrame(self.centralwidget)
        self.frame_auto_5.setObjectName(u"frame_auto_5")
        self.frame_auto_5.setGeometry(QRect(680, 460, 171, 221))
        self.frame_auto_5.setStyleSheet(u"QFrame{\n"
"border-image: url(/home/chris/emc-dev/share/qtscreen/images/frame_bg_grey.png) 0 0 0 0 stretch stretch;}")
        self.frame_auto_5.setFrameShape(QFrame.StyledPanel)
        self.frame_auto_5.setFrameShadow(QFrame.Raised)
        self.statuslabel = StatusLabel(self.frame_auto_5)
        self.statuslabel.setObjectName(u"statuslabel")
        self.statuslabel.setGeometry(QRect(10, 110, 151, 21))
        self.statuslabel.setProperty("gcodes_status", False)
        self.statuslabel.setProperty("tool_comment_status", True)
        self.StatusLabel = StatusLabel(self.centralwidget)
        self.StatusLabel.setObjectName(u"StatusLabel")
        self.StatusLabel.setGeometry(QRect(760, 530, 91, 31))
        self.StatusLabel.setProperty("tool_number_status", False)
        self.StatusLabel.setProperty("tool_diameter_status", True)
        self.state_label_10 = StatusLabel(self.centralwidget)
        self.state_label_10.setObjectName(u"state_label_10")
        self.state_label_10.setGeometry(QRect(410, 590, 251, 31))
        self.state_label_10.setTextFormat(Qt.RichText)
        self.state_label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.state_label_10.setProperty("feed_override_status", False)
        self.state_label_10.setProperty("spindle_override_status", False)
        self.state_label_10.setProperty("requested_spindle_speed_status", False)
        self.state_label_10.setProperty("actual_spindle_speed_status", False)
        self.state_label_10.setProperty("actual_surface_speed_status", True)
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(1029, -1, 751, 761))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.xembed = XEmbed(self.horizontalLayoutWidget)
        self.xembed.setObjectName(u"xembed")

        self.horizontalLayout.addWidget(self.xembed)

        MainWindow.setCentralWidget(self.centralwidget)
        self.lcncdialog.raise_()
        self.frame_auto_5.raise_()
        self.state_label_4.raise_()
        self.StatusLabel.raise_()
        self.frame_auto_10.raise_()
        self.frame_auto_9.raise_()
        self.frame_auto_6.raise_()
        self.frame_auto_7.raise_()
        self.frame_auto_4.raise_()
        self.frame_auto_3.raise_()
        self.frame_auto_2.raise_()
        self.drolabel_y.raise_()
        self.drolabel_z.raise_()
        self.drolabel_x.raise_()
        self.frame.raise_()
        self.gcodeeditor.raise_()
        self.state_enable_gridLayout.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.line.raise_()
        self.state_label.raise_()
        self.state_label_2.raise_()
        self.state_label_3.raise_()
        self.state_label_5.raise_()
        self.state_label_6.raise_()
        self.tooldialog.raise_()
        self.filedialog.raise_()
        self.led_home_x.raise_()
        self.led_home_y.raise_()
        self.led_home_z.raise_()
        self.actionbutton_9.raise_()
        self.actionbutton_10.raise_()
        self.actionbutton_11.raise_()
        self.ScreenOptions.raise_()
        self.StatusLabel_2.raise_()
        self.macrotabdialog.raise_()
        self.originoffsetdialog.raise_()
        self.StatusStacked.raise_()
        self.StatusSlider.raise_()
        self.StatusSlider_2.raise_()
        self.StatusSlider_6.raise_()
        self.StatusSlider_5.raise_()
        self.mcodes_label.raise_()
        self.actionbutton_15.raise_()
        self.actionbutton_16.raise_()
        self.actionbutton_17.raise_()
        self.actionbutton_18.raise_()
        self.frame_auto_8.raise_()
        self.gcodes_label.raise_()
        self.state_label_10.raise_()
        self.focusoverlay.raise_()
        self.horizontalLayoutWidget.raise_()
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)

        self.StatusStacked.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.drolabel_z.setText(QCoreApplication.translate("MainWindow", u"   0.5217", None))
        self.drolabel_x.setText(QCoreApplication.translate("MainWindow", u"  -1.6994", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.state_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>  <span style=\" font-weight:600; font-size:18pt; color:#ffff00;\">100.0</span></p></body></html>", None))
        self.state_label_7.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p>  <span style=\" font-weight:600; font-size:18pt; color:#ffff00;\">%3.1f</span></p></body></html>", None))
        self.StateLabel.setText("")
        self.StateLabel.setProperty("true_textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#ffff00;\">MM</span></p></body></html>", None))
        self.StateLabel.setProperty("false_textTemplate", "")
        self.StateLabel_2.setText("")
        self.StateLabel_2.setProperty("true_textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#ffff00;\">DIAM</span></p></body></html>", None))
        self.StateLabel_2.setProperty("false_textTemplate", "")
        self.state_label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>  <span style=\" font-weight:600; font-size:18pt; color:#ffff00;\">100.000</span></p></body></html>", None))
        self.state_label_9.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p>  <span style=\" font-weight:600; font-size:18pt; color:#ffff00;\">%3.3f</span></p></body></html>", None))
        self.state_label_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#ffff00;\">G100.0</span></p></body></html>", None))
        self.state_label_8.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#ffff00;\">G%s</span></p></body></html>", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Velocity:", None))
        self.statelabel_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#fffffd;\">IPR:</span></p></body></html>", None))
        self.statelabel_3.setProperty("true_textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#fffffd;\">mmPR:</span></p></body></html>", None))
        self.statelabel_3.setProperty("false_textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#fffffd;\">IPR:</span></p></body></html>", None))
        self.actionbutton.setText(QCoreApplication.translate("MainWindow", u"Zero Z", None))
        self.actionbutton_2.setText(QCoreApplication.translate("MainWindow", u"Zero Y", None))
        self.actionbutton_3.setText(QCoreApplication.translate("MainWindow", u"Zero X", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#d1d1d1;;\">Jog Rate</span></p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#d1d1d1;\">Jog Inc</span></p></body></html>", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#d1d1d1;\">Number</span></p></body></html>", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#d1d1d1;\">Diameter</span></p></body></html>", None))
        self.state_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#d0d0d0;\">RO:</span><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">100%</span></p></body></html>", None))
        self.state_label.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#d0d0d0;\">RO:</span><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">%3.f%%</span></p></body></html>", None))
        self.state_label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#d0d0d0;\">FO:</span><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">100%</span></p></body></html>", None))
        self.state_label_2.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#d0d0d0;\">FO:</span><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">%3.f%%</span></p></body></html>", None))
        self.state_label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#d0d0d0;\">SO:</span><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">100%</span></p></body></html>", None))
        self.state_label_3.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#d0d0d0;\">SO:</span><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">%3.f%%</span></p></body></html>", None))
        self.state_label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>   <span style=\" font-weight:600;font-size:18pt;  color:#ffff00;\">100</span></p></body></html>", None))
        self.state_label_4.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p>   <span style=\" font-weight:600;font-size:18pt;  color:#ffff00;\">%d</span></p></body></html>", None))
        self.state_label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#ffff00;\">100</span></p></body></html>", None))
        self.state_label_5.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#ffff00;\">%2.f</span></p></body></html>", None))
        self.state_label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:36pt; color:#ffff00;\">100</span><span style=\" font-size:36pt; color:#d1d1d1;\"> RPM</span></p></body></html>", None))
        self.state_label_6.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:36pt; color:#ffff00;\">%d</span><span style=\" font-size:36pt; color:#d1d1d1;\"> RPM</span></p></body></html>", None))
        self.focusoverlay.setProperty("image_path", QCoreApplication.translate("MainWindow", u"STD_IMAGE_DIR/lcnc_swoop.png", None))
        self.actionbutton_9.setText(QCoreApplication.translate("MainWindow", u"MAN", None))
        self.actionbutton_10.setText(QCoreApplication.translate("MainWindow", u"MDI", None))
        self.actionbutton_11.setText(QCoreApplication.translate("MainWindow", u"AUTO", None))
        self.StatusLabel_2.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#ffff00;\">%s</span></p></body></html>", None))
        self.jog_pos_x.setText(QCoreApplication.translate("MainWindow", u"X+", None))
        self.jog_neg_x.setText(QCoreApplication.translate("MainWindow", u"X-", None))
        self.jog_pos_z.setText(QCoreApplication.translate("MainWindow", u"Z+", None))
        self.jog_neg_z.setText(QCoreApplication.translate("MainWindow", u"Z-", None))
        self.jog_neg_y.setText(QCoreApplication.translate("MainWindow", u"Y-", None))
        self.jog_pos_y.setText(QCoreApplication.translate("MainWindow", u"Y+", None))
        self.button_home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.actionbutton_25.setText(QCoreApplication.translate("MainWindow", u"Fwd", None))
        self.actionbutton_26.setText(QCoreApplication.translate("MainWindow", u"Rev", None))
        self.actionbutton_27.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.actionbutton_28.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.actionbutton_29.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.actionbutton_14.setText(QCoreApplication.translate("MainWindow", u"offsets", None))
        self.actionbutton_13.setText(QCoreApplication.translate("MainWindow", u"Cam View", None))
        self.actionbutton_12.setText(QCoreApplication.translate("MainWindow", u"Macro", None))
        self.actionbutton_32.setText(QCoreApplication.translate("MainWindow", u"Go to\n"
"Origin Zero", None))
        self.actionbutton_32.setProperty("command_text_string", QCoreApplication.translate("MainWindow", u"MDI_COMMAND_LIST = 0", None))
        self.actionbutton_33.setText(QCoreApplication.translate("MainWindow", u"Go to\n"
" Machine Zero", None))
        self.actionbutton_33.setProperty("command_text_string", QCoreApplication.translate("MainWindow", u"G53 G0 X0Y0Z0", None))
        self.actionbutton_load.setText(QCoreApplication.translate("MainWindow", u"load\n"
"file", None))
        self.actionbutton_4.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.actionbutton_19.setText(QCoreApplication.translate("MainWindow", u"View P", None))
        self.actionbutton_20.setText(QCoreApplication.translate("MainWindow", u"View Z", None))
        self.actionbutton_20.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"z", None))
        self.actionbutton_21.setText(QCoreApplication.translate("MainWindow", u"View Y", None))
        self.actionbutton_21.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"y", None))
        self.actionbutton_22.setText(QCoreApplication.translate("MainWindow", u"View X", None))
        self.actionbutton_22.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"x", None))
        self.actionbutton_23.setText(QCoreApplication.translate("MainWindow", u"View Y2", None))
        self.actionbutton_23.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"y2", None))
        self.actionbutton_24.setText(QCoreApplication.translate("MainWindow", u"View Z2", None))
        self.actionbutton_24.setProperty("view_type_string", QCoreApplication.translate("MainWindow", u"z2", None))
        self.mcodes_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; color:#ffff00;\">Mcodes: </span><span style=\" color:#ffff00;\">100.0</span></p></body></html>", None))
        self.mcodes_label.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; color:#ffff00;\">Mcodes: </span><span style=\" color:#ffff00;\">%s</span></p></body></html>", None))
        self.actionbutton_15.setText(QCoreApplication.translate("MainWindow", u"FO", None))
        self.actionbutton_16.setText(QCoreApplication.translate("MainWindow", u"RO", None))
        self.actionbutton_17.setText(QCoreApplication.translate("MainWindow", u"SO", None))
        self.actionbutton_18.setText(QCoreApplication.translate("MainWindow", u"Jog", None))
        self.actionbutton_override_limits.setText(QCoreApplication.translate("MainWindow", u"Override Limits ", None))
        self.button_estop.setText(QCoreApplication.translate("MainWindow", u"Estop  ", None))
        self.button_machineon.setText(QCoreApplication.translate("MainWindow", u"Power ", None))
        self.actionbutton_flood.setText(QCoreApplication.translate("MainWindow", u"Flood", None))
        self.actionbutton_mist.setText(QCoreApplication.translate("MainWindow", u"Mist", None))
        self.actionbutton_block_delete.setText(QCoreApplication.translate("MainWindow", u"Block Delete", None))
        self.actionbutton_optional_stop.setText(QCoreApplication.translate("MainWindow", u"Optional Stop", None))
        self.actionbutton_6.setText(QCoreApplication.translate("MainWindow", u"Abort", None))
        self.actionbutton_5.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.actionbutton_7.setText(QCoreApplication.translate("MainWindow", u"Fine", None))
        self.actionbutton_8.setText(QCoreApplication.translate("MainWindow", u"Med", None))
        self.actionbutton_30.setText(QCoreApplication.translate("MainWindow", u"Large", None))
        self.actionbutton_31.setText(QCoreApplication.translate("MainWindow", u"Continuous", None))
        self.mdi_line.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; color:#ffff00;\">MDI:</span></p></body></html>", None))
        self.gcodes_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; color:#ffff00;\">Gcodes: </span><span style=\" color:#ffff00;\">100.0</span></p></body></html>", None))
        self.gcodes_label.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; color:#ffff00;\">Gcodes: </span><span style=\" color:#ffff00;\">%s</span></p></body></html>", None))
        self.statuslabel.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#d1d1d1;\">%s</span></p></body></html>", None))
        self.StatusLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>   <span style=\" font-weight:600;font-size:18pt;  color:#ffff00;\">100.000</span></p></body></html>", None))
        self.StatusLabel.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p>   <span style=\" font-weight:600;font-size:18pt;  color:#ffff00;\">%3.3f</span></p></body></html>", None))
        self.state_label_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#ffff00;\">200.00</span><span style=\" font-size:18pt; color:#d1d1d1;\"> SFPM</span></p></body></html>", None))
        self.state_label_10.setProperty("textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#ffff00;\">%.2f</span><span style=\" font-size:18pt; color:#d1d1d1;\"> SFPM</span></p></body></html>", None))
        self.state_label_10.setProperty("alt_textTemplate", QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#ffff00;\">%.2f</span><span style=\" font-size:18pt; color:#d1d1d1;\"> SMPM</span></p></body></html>", None))
        self.xembed.setProperty("command_string", QCoreApplication.translate("MainWindow", u"halcmd loadusr gladevcp --xid pyngcgui.ui", None))
    # retranslateUi

