# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'versa_probe.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from qtvcp.widgets.led_widget import LED
from qtvcp.widgets.simple_widgets import PushButton


class Ui_versaProbe(object):
    def setupUi(self, versaProbe):
        if not versaProbe.objectName():
            versaProbe.setObjectName(u"versaProbe")
        versaProbe.resize(650, 440)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(versaProbe.sizePolicy().hasHeightForWidth())
        versaProbe.setSizePolicy(sizePolicy)
        versaProbe.setMinimumSize(QSize(650, 440))
        self.horizontalLayout = QHBoxLayout(versaProbe)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget_probing = QWidget(versaProbe)
        self.widget_probing.setObjectName(u"widget_probing")
        self.verticalLayout_8 = QVBoxLayout(self.widget_probing)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.widget_top = QWidget(self.widget_probing)
        self.widget_top.setObjectName(u"widget_top")
        self.widget_top.setMinimumSize(QSize(0, 0))
        self.horizontalLayout_14 = QHBoxLayout(self.widget_top)
        self.horizontalLayout_14.setSpacing(4)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.widget_outside_measure = QWidget(self.widget_top)
        self.widget_outside_measure.setObjectName(u"widget_outside_measure")
        self.widget_outside_measure.setMinimumSize(QSize(170, 0))
        self.verticalLayout_2 = QVBoxLayout(self.widget_outside_measure)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_outside_measure = QLabel(self.widget_outside_measure)
        self.label_outside_measure.setObjectName(u"label_outside_measure")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_outside_measure.sizePolicy().hasHeightForWidth())
        self.label_outside_measure.setSizePolicy(sizePolicy1)
        self.label_outside_measure.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_outside_measure)

        self.widget_outside_btns = QWidget(self.widget_outside_measure)
        self.widget_outside_btns.setObjectName(u"widget_outside_btns")
        sizePolicy.setHeightForWidth(self.widget_outside_btns.sizePolicy().hasHeightForWidth())
        self.widget_outside_btns.setSizePolicy(sizePolicy)
        self.widget_outside_btns.setMinimumSize(QSize(166, 166))
        self.widget_outside_btns.setMaximumSize(QSize(16777215, 1677215))
        self.gridLayout_3 = QGridLayout(self.widget_outside_btns)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.pbtn_outside_xpym = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup = QButtonGroup(versaProbe)
        self.outside_buttonGroup.setObjectName(u"outside_buttonGroup")
        self.outside_buttonGroup.setExclusive(False)
        self.outside_buttonGroup.addButton(self.pbtn_outside_xpym)
        self.pbtn_outside_xpym.setObjectName(u"pbtn_outside_xpym")
        sizePolicy.setHeightForWidth(self.pbtn_outside_xpym.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_xpym.setSizePolicy(sizePolicy)
        self.pbtn_outside_xpym.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_xpym.setMaximumSize(QSize(50, 50))
        icon = QIcon()
        icon.addFile(u"../images/probe_icons/X+Y-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_xpym.setIcon(icon)
        self.pbtn_outside_xpym.setIconSize(QSize(48, 48))
        self.pbtn_outside_xpym.setCheckable(False)
        self.pbtn_outside_xpym.setChecked(False)
        self.pbtn_outside_xpym.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_xpym, 0, 0, 1, 1)

        self.pbtn_outside_ym = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_ym)
        self.pbtn_outside_ym.setObjectName(u"pbtn_outside_ym")
        sizePolicy.setHeightForWidth(self.pbtn_outside_ym.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_ym.setSizePolicy(sizePolicy)
        self.pbtn_outside_ym.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_ym.setMaximumSize(QSize(50, 50))
        icon1 = QIcon()
        icon1.addFile(u"../images/probe_icons/Y-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_ym.setIcon(icon1)
        self.pbtn_outside_ym.setIconSize(QSize(48, 48))
        self.pbtn_outside_ym.setCheckable(False)
        self.pbtn_outside_ym.setChecked(False)
        self.pbtn_outside_ym.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_ym, 0, 1, 1, 1)

        self.pbtn_outside_xmym = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_xmym)
        self.pbtn_outside_xmym.setObjectName(u"pbtn_outside_xmym")
        sizePolicy.setHeightForWidth(self.pbtn_outside_xmym.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_xmym.setSizePolicy(sizePolicy)
        self.pbtn_outside_xmym.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_xmym.setMaximumSize(QSize(50, 50))
        icon2 = QIcon()
        icon2.addFile(u"../images/probe_icons/X-Y-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_xmym.setIcon(icon2)
        self.pbtn_outside_xmym.setIconSize(QSize(48, 48))
        self.pbtn_outside_xmym.setCheckable(False)
        self.pbtn_outside_xmym.setChecked(False)
        self.pbtn_outside_xmym.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_xmym, 0, 2, 1, 1)

        self.pbtn_outside_xp = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_xp)
        self.pbtn_outside_xp.setObjectName(u"pbtn_outside_xp")
        sizePolicy.setHeightForWidth(self.pbtn_outside_xp.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_xp.setSizePolicy(sizePolicy)
        self.pbtn_outside_xp.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_xp.setMaximumSize(QSize(50, 50))
        icon3 = QIcon()
        icon3.addFile(u"../images/probe_icons/X+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_xp.setIcon(icon3)
        self.pbtn_outside_xp.setIconSize(QSize(48, 48))
        self.pbtn_outside_xp.setCheckable(False)
        self.pbtn_outside_xp.setChecked(False)
        self.pbtn_outside_xp.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_xp, 1, 0, 1, 1)

        self.pbtn_outside_center = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_center)
        self.pbtn_outside_center.setObjectName(u"pbtn_outside_center")
        sizePolicy.setHeightForWidth(self.pbtn_outside_center.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_center.setSizePolicy(sizePolicy)
        self.pbtn_outside_center.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_center.setMaximumSize(QSize(50, 50))
        font = QFont()
        font.setPointSize(8)
        self.pbtn_outside_center.setFont(font)
        icon4 = QIcon()
        icon4.addFile(u"../images/probe_icons/xy_center.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_center.setIcon(icon4)
        self.pbtn_outside_center.setIconSize(QSize(48, 48))
        self.pbtn_outside_center.setCheckable(False)
        self.pbtn_outside_center.setChecked(False)
        self.pbtn_outside_center.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_center, 1, 1, 1, 1)

        self.pbtn_outside_xm = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_xm)
        self.pbtn_outside_xm.setObjectName(u"pbtn_outside_xm")
        sizePolicy.setHeightForWidth(self.pbtn_outside_xm.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_xm.setSizePolicy(sizePolicy)
        self.pbtn_outside_xm.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_xm.setMaximumSize(QSize(50, 50))
        icon5 = QIcon()
        icon5.addFile(u"../images/probe_icons/X-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_xm.setIcon(icon5)
        self.pbtn_outside_xm.setIconSize(QSize(48, 48))
        self.pbtn_outside_xm.setCheckable(False)
        self.pbtn_outside_xm.setChecked(False)
        self.pbtn_outside_xm.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_xm, 1, 2, 1, 1)

        self.pbtn_outside_xpyp = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_xpyp)
        self.pbtn_outside_xpyp.setObjectName(u"pbtn_outside_xpyp")
        sizePolicy.setHeightForWidth(self.pbtn_outside_xpyp.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_xpyp.setSizePolicy(sizePolicy)
        self.pbtn_outside_xpyp.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_xpyp.setMaximumSize(QSize(50, 50))
        icon6 = QIcon()
        icon6.addFile(u"../images/probe_icons/X+Y+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_xpyp.setIcon(icon6)
        self.pbtn_outside_xpyp.setIconSize(QSize(48, 48))
        self.pbtn_outside_xpyp.setCheckable(False)
        self.pbtn_outside_xpyp.setChecked(False)
        self.pbtn_outside_xpyp.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_xpyp, 2, 0, 1, 1)

        self.pbtn_outside_yp = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_yp)
        self.pbtn_outside_yp.setObjectName(u"pbtn_outside_yp")
        sizePolicy.setHeightForWidth(self.pbtn_outside_yp.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_yp.setSizePolicy(sizePolicy)
        self.pbtn_outside_yp.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_yp.setMaximumSize(QSize(50, 50))
        icon7 = QIcon()
        icon7.addFile(u"../images/probe_icons/Y+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_yp.setIcon(icon7)
        self.pbtn_outside_yp.setIconSize(QSize(48, 48))
        self.pbtn_outside_yp.setCheckable(False)
        self.pbtn_outside_yp.setChecked(False)
        self.pbtn_outside_yp.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_yp, 2, 1, 1, 1)

        self.pbtn_outside_xmyp = PushButton(self.widget_outside_btns)
        self.outside_buttonGroup.addButton(self.pbtn_outside_xmyp)
        self.pbtn_outside_xmyp.setObjectName(u"pbtn_outside_xmyp")
        sizePolicy.setHeightForWidth(self.pbtn_outside_xmyp.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_xmyp.setSizePolicy(sizePolicy)
        self.pbtn_outside_xmyp.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_xmyp.setMaximumSize(QSize(50, 50))
        icon8 = QIcon()
        icon8.addFile(u"../images/probe_icons/X-Y+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_xmyp.setIcon(icon8)
        self.pbtn_outside_xmyp.setIconSize(QSize(48, 48))
        self.pbtn_outside_xmyp.setCheckable(False)
        self.pbtn_outside_xmyp.setChecked(False)
        self.pbtn_outside_xmyp.setProperty("indicator_option", False)

        self.gridLayout_3.addWidget(self.pbtn_outside_xmyp, 2, 2, 1, 1)


        self.verticalLayout_2.addWidget(self.widget_outside_btns)

        self.widget_offsets = QWidget(self.widget_outside_measure)
        self.widget_offsets.setObjectName(u"widget_offsets")
        self.widget_offsets.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_28 = QHBoxLayout(self.widget_offsets)
        self.horizontalLayout_28.setSpacing(4)
        self.horizontalLayout_28.setObjectName(u"horizontalLayout_28")
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.widget_adjust = QWidget(self.widget_offsets)
        self.widget_adjust.setObjectName(u"widget_adjust")
        self.widget_adjust.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_13 = QVBoxLayout(self.widget_adjust)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.label_adjust = QLabel(self.widget_adjust)
        self.label_adjust.setObjectName(u"label_adjust")
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        self.label_adjust.setFont(font1)
        self.label_adjust.setFrameShape(QFrame.NoFrame)
        self.label_adjust.setFrameShadow(QFrame.Plain)
        self.label_adjust.setAlignment(Qt.AlignCenter)
        self.label_adjust.setMargin(4)

        self.verticalLayout_13.addWidget(self.label_adjust)

        self.widget_x_offset = QWidget(self.widget_adjust)
        self.widget_x_offset.setObjectName(u"widget_x_offset")
        self.horizontalLayout_31 = QHBoxLayout(self.widget_x_offset)
        self.horizontalLayout_31.setSpacing(4)
        self.horizontalLayout_31.setObjectName(u"horizontalLayout_31")
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.label_x = QLabel(self.widget_x_offset)
        self.label_x.setObjectName(u"label_x")
        self.label_x.setMinimumSize(QSize(20, 0))
        self.label_x.setAlignment(Qt.AlignCenter)
        self.label_x.setMargin(2)

        self.horizontalLayout_31.addWidget(self.label_x)

        self.input_adj_x = QLineEdit(self.widget_x_offset)
        self.input_adj_x.setObjectName(u"input_adj_x")
        sizePolicy.setHeightForWidth(self.input_adj_x.sizePolicy().hasHeightForWidth())
        self.input_adj_x.setSizePolicy(sizePolicy)
        self.input_adj_x.setMinimumSize(QSize(70, 24))
        self.input_adj_x.setMaximumSize(QSize(70, 24))
        font2 = QFont()
        font2.setPointSize(10)
        self.input_adj_x.setFont(font2)
        self.input_adj_x.setCursor(QCursor(Qt.IBeamCursor))
        self.input_adj_x.setAutoFillBackground(False)
        self.input_adj_x.setMaxLength(7)
        self.input_adj_x.setFrame(True)
        self.input_adj_x.setCursorPosition(0)
        self.input_adj_x.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_31.addWidget(self.input_adj_x)


        self.verticalLayout_13.addWidget(self.widget_x_offset)

        self.widget_y_offset = QWidget(self.widget_adjust)
        self.widget_y_offset.setObjectName(u"widget_y_offset")
        self.horizontalLayout_32 = QHBoxLayout(self.widget_y_offset)
        self.horizontalLayout_32.setSpacing(4)
        self.horizontalLayout_32.setObjectName(u"horizontalLayout_32")
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.label_y = QLabel(self.widget_y_offset)
        self.label_y.setObjectName(u"label_y")
        self.label_y.setMinimumSize(QSize(20, 0))
        self.label_y.setAlignment(Qt.AlignCenter)
        self.label_y.setMargin(2)

        self.horizontalLayout_32.addWidget(self.label_y)

        self.input_adj_y = QLineEdit(self.widget_y_offset)
        self.input_adj_y.setObjectName(u"input_adj_y")
        sizePolicy.setHeightForWidth(self.input_adj_y.sizePolicy().hasHeightForWidth())
        self.input_adj_y.setSizePolicy(sizePolicy)
        self.input_adj_y.setMinimumSize(QSize(70, 24))
        self.input_adj_y.setMaximumSize(QSize(70, 24))
        self.input_adj_y.setFont(font2)
        self.input_adj_y.setCursor(QCursor(Qt.IBeamCursor))
        self.input_adj_y.setMaxLength(7)
        self.input_adj_y.setFrame(True)
        self.input_adj_y.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_32.addWidget(self.input_adj_y)


        self.verticalLayout_13.addWidget(self.widget_y_offset)

        self.widget_z_offset = QWidget(self.widget_adjust)
        self.widget_z_offset.setObjectName(u"widget_z_offset")
        self.horizontalLayout_33 = QHBoxLayout(self.widget_z_offset)
        self.horizontalLayout_33.setSpacing(4)
        self.horizontalLayout_33.setObjectName(u"horizontalLayout_33")
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.label_z = QLabel(self.widget_z_offset)
        self.label_z.setObjectName(u"label_z")
        self.label_z.setMinimumSize(QSize(20, 0))
        self.label_z.setAlignment(Qt.AlignCenter)
        self.label_z.setMargin(2)

        self.horizontalLayout_33.addWidget(self.label_z)

        self.input_adj_z = QLineEdit(self.widget_z_offset)
        self.input_adj_z.setObjectName(u"input_adj_z")
        sizePolicy.setHeightForWidth(self.input_adj_z.sizePolicy().hasHeightForWidth())
        self.input_adj_z.setSizePolicy(sizePolicy)
        self.input_adj_z.setMinimumSize(QSize(70, 24))
        self.input_adj_z.setMaximumSize(QSize(70, 24))
        self.input_adj_z.setFont(font2)
        self.input_adj_z.setCursor(QCursor(Qt.IBeamCursor))
        self.input_adj_z.setMaxLength(7)
        self.input_adj_z.setFrame(True)
        self.input_adj_z.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_33.addWidget(self.input_adj_z)


        self.verticalLayout_13.addWidget(self.widget_z_offset)

        self.widget_a_offset = QWidget(self.widget_adjust)
        self.widget_a_offset.setObjectName(u"widget_a_offset")
        self.horizontalLayout_34 = QHBoxLayout(self.widget_a_offset)
        self.horizontalLayout_34.setSpacing(4)
        self.horizontalLayout_34.setObjectName(u"horizontalLayout_34")
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.label_adjust_angle = QLabel(self.widget_a_offset)
        self.label_adjust_angle.setObjectName(u"label_adjust_angle")
        self.label_adjust_angle.setMinimumSize(QSize(20, 0))
        self.label_adjust_angle.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_34.addWidget(self.label_adjust_angle)

        self.input_adj_angle = QLineEdit(self.widget_a_offset)
        self.input_adj_angle.setObjectName(u"input_adj_angle")
        sizePolicy.setHeightForWidth(self.input_adj_angle.sizePolicy().hasHeightForWidth())
        self.input_adj_angle.setSizePolicy(sizePolicy)
        self.input_adj_angle.setMinimumSize(QSize(70, 24))
        self.input_adj_angle.setMaximumSize(QSize(70, 24))
        self.input_adj_angle.setFont(font2)
        self.input_adj_angle.setCursor(QCursor(Qt.IBeamCursor))
        self.input_adj_angle.setMaxLength(5)
        self.input_adj_angle.setFrame(True)
        self.input_adj_angle.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_34.addWidget(self.input_adj_angle)


        self.verticalLayout_13.addWidget(self.widget_a_offset)


        self.horizontalLayout_28.addWidget(self.widget_adjust)

        self.widget_set_xyz = QWidget(self.widget_offsets)
        self.widget_set_xyz.setObjectName(u"widget_set_xyz")
        self.verticalLayout_5 = QVBoxLayout(self.widget_set_xyz)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.pbtn_set_x = PushButton(self.widget_set_xyz)
        self.pbtn_set_x.setObjectName(u"pbtn_set_x")
        sizePolicy.setHeightForWidth(self.pbtn_set_x.sizePolicy().hasHeightForWidth())
        self.pbtn_set_x.setSizePolicy(sizePolicy)
        self.pbtn_set_x.setMinimumSize(QSize(50, 40))
        self.pbtn_set_x.setMaximumSize(QSize(50, 40))
        self.pbtn_set_x.setCheckable(False)
        self.pbtn_set_x.setChecked(False)
        self.pbtn_set_x.setProperty("indicator_option", False)

        self.verticalLayout_5.addWidget(self.pbtn_set_x)

        self.pbtn_set_y = PushButton(self.widget_set_xyz)
        self.pbtn_set_y.setObjectName(u"pbtn_set_y")
        sizePolicy.setHeightForWidth(self.pbtn_set_y.sizePolicy().hasHeightForWidth())
        self.pbtn_set_y.setSizePolicy(sizePolicy)
        self.pbtn_set_y.setMinimumSize(QSize(50, 40))
        self.pbtn_set_y.setMaximumSize(QSize(50, 40))
        self.pbtn_set_y.setCheckable(False)
        self.pbtn_set_y.setChecked(False)
        self.pbtn_set_y.setProperty("indicator_option", False)

        self.verticalLayout_5.addWidget(self.pbtn_set_y)

        self.pbtn_set_z = PushButton(self.widget_set_xyz)
        self.pbtn_set_z.setObjectName(u"pbtn_set_z")
        sizePolicy.setHeightForWidth(self.pbtn_set_z.sizePolicy().hasHeightForWidth())
        self.pbtn_set_z.setSizePolicy(sizePolicy)
        self.pbtn_set_z.setMinimumSize(QSize(50, 40))
        self.pbtn_set_z.setMaximumSize(QSize(50, 40))
        self.pbtn_set_z.setCheckable(False)
        self.pbtn_set_z.setChecked(False)
        self.pbtn_set_z.setProperty("indicator_option", False)

        self.verticalLayout_5.addWidget(self.pbtn_set_z)


        self.horizontalLayout_28.addWidget(self.widget_set_xyz, 0, Qt.AlignHCenter)


        self.verticalLayout_2.addWidget(self.widget_offsets)


        self.horizontalLayout_14.addWidget(self.widget_outside_measure)

        self.widget_inside_measure = QWidget(self.widget_top)
        self.widget_inside_measure.setObjectName(u"widget_inside_measure")
        self.widget_inside_measure.setMinimumSize(QSize(170, 0))
        self.verticalLayout = QVBoxLayout(self.widget_inside_measure)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_inside_measure = QLabel(self.widget_inside_measure)
        self.label_inside_measure.setObjectName(u"label_inside_measure")
        sizePolicy1.setHeightForWidth(self.label_inside_measure.sizePolicy().hasHeightForWidth())
        self.label_inside_measure.setSizePolicy(sizePolicy1)
        self.label_inside_measure.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label_inside_measure)

        self.widget_inside_btns = QWidget(self.widget_inside_measure)
        self.widget_inside_btns.setObjectName(u"widget_inside_btns")
        sizePolicy.setHeightForWidth(self.widget_inside_btns.sizePolicy().hasHeightForWidth())
        self.widget_inside_btns.setSizePolicy(sizePolicy)
        self.widget_inside_btns.setMinimumSize(QSize(166, 166))
        self.widget_inside_btns.setMaximumSize(QSize(16777215, 16777215))
        self.gridLayout = QGridLayout(self.widget_inside_btns)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.pbtn_inside_xmyp = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup = QButtonGroup(versaProbe)
        self.inside_buttonGroup.setObjectName(u"inside_buttonGroup")
        self.inside_buttonGroup.setExclusive(False)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xmyp)
        self.pbtn_inside_xmyp.setObjectName(u"pbtn_inside_xmyp")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xmyp.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xmyp.setSizePolicy(sizePolicy)
        self.pbtn_inside_xmyp.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xmyp.setMaximumSize(QSize(50, 50))
        icon9 = QIcon()
        icon9.addFile(u"../images/probe_icons/inX-Y+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xmyp.setIcon(icon9)
        self.pbtn_inside_xmyp.setIconSize(QSize(48, 48))
        self.pbtn_inside_xmyp.setCheckable(False)
        self.pbtn_inside_xmyp.setChecked(False)
        self.pbtn_inside_xmyp.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xmyp, 0, 0, 1, 1)

        self.pbtn_inside_yp = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_yp)
        self.pbtn_inside_yp.setObjectName(u"pbtn_inside_yp")
        sizePolicy.setHeightForWidth(self.pbtn_inside_yp.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_yp.setSizePolicy(sizePolicy)
        self.pbtn_inside_yp.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_yp.setMaximumSize(QSize(50, 50))
        icon10 = QIcon()
        icon10.addFile(u"../images/probe_icons/inY+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_yp.setIcon(icon10)
        self.pbtn_inside_yp.setIconSize(QSize(48, 48))
        self.pbtn_inside_yp.setCheckable(False)
        self.pbtn_inside_yp.setChecked(False)
        self.pbtn_inside_yp.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_yp, 0, 1, 1, 1)

        self.pbtn_inside_xpyp = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xpyp)
        self.pbtn_inside_xpyp.setObjectName(u"pbtn_inside_xpyp")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xpyp.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xpyp.setSizePolicy(sizePolicy)
        self.pbtn_inside_xpyp.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xpyp.setMaximumSize(QSize(50, 50))
        icon11 = QIcon()
        icon11.addFile(u"../images/probe_icons/inX+Y+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xpyp.setIcon(icon11)
        self.pbtn_inside_xpyp.setIconSize(QSize(48, 48))
        self.pbtn_inside_xpyp.setCheckable(False)
        self.pbtn_inside_xpyp.setChecked(False)
        self.pbtn_inside_xpyp.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xpyp, 0, 2, 1, 1)

        self.pbtn_inside_xm = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xm)
        self.pbtn_inside_xm.setObjectName(u"pbtn_inside_xm")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xm.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xm.setSizePolicy(sizePolicy)
        self.pbtn_inside_xm.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xm.setMaximumSize(QSize(50, 50))
        icon12 = QIcon()
        icon12.addFile(u"../images/probe_icons/inX-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xm.setIcon(icon12)
        self.pbtn_inside_xm.setIconSize(QSize(48, 48))
        self.pbtn_inside_xm.setCheckable(False)
        self.pbtn_inside_xm.setChecked(False)
        self.pbtn_inside_xm.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xm, 1, 0, 1, 1)

        self.pbtn_inside_xy_hole = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xy_hole)
        self.pbtn_inside_xy_hole.setObjectName(u"pbtn_inside_xy_hole")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xy_hole.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xy_hole.setSizePolicy(sizePolicy)
        self.pbtn_inside_xy_hole.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xy_hole.setMaximumSize(QSize(50, 50))
        self.pbtn_inside_xy_hole.setFont(font)
        icon13 = QIcon()
        icon13.addFile(u"../images/probe_icons/inHole.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xy_hole.setIcon(icon13)
        self.pbtn_inside_xy_hole.setIconSize(QSize(48, 48))
        self.pbtn_inside_xy_hole.setCheckable(False)
        self.pbtn_inside_xy_hole.setChecked(False)
        self.pbtn_inside_xy_hole.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xy_hole, 1, 1, 1, 1)

        self.pbtn_inside_xp = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xp)
        self.pbtn_inside_xp.setObjectName(u"pbtn_inside_xp")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xp.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xp.setSizePolicy(sizePolicy)
        self.pbtn_inside_xp.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xp.setMaximumSize(QSize(50, 50))
        icon14 = QIcon()
        icon14.addFile(u"../images/probe_icons/inX+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xp.setIcon(icon14)
        self.pbtn_inside_xp.setIconSize(QSize(48, 48))
        self.pbtn_inside_xp.setCheckable(False)
        self.pbtn_inside_xp.setChecked(False)
        self.pbtn_inside_xp.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xp, 1, 2, 1, 1)

        self.pbtn_inside_xmym = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xmym)
        self.pbtn_inside_xmym.setObjectName(u"pbtn_inside_xmym")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xmym.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xmym.setSizePolicy(sizePolicy)
        self.pbtn_inside_xmym.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xmym.setMaximumSize(QSize(50, 50))
        icon15 = QIcon()
        icon15.addFile(u"../images/probe_icons/inX-Y-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xmym.setIcon(icon15)
        self.pbtn_inside_xmym.setIconSize(QSize(48, 48))
        self.pbtn_inside_xmym.setCheckable(False)
        self.pbtn_inside_xmym.setChecked(False)
        self.pbtn_inside_xmym.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xmym, 2, 0, 1, 1)

        self.pbtn_inside_ym = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_ym)
        self.pbtn_inside_ym.setObjectName(u"pbtn_inside_ym")
        sizePolicy.setHeightForWidth(self.pbtn_inside_ym.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_ym.setSizePolicy(sizePolicy)
        self.pbtn_inside_ym.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_ym.setMaximumSize(QSize(50, 50))
        icon16 = QIcon()
        icon16.addFile(u"../images/probe_icons/inY-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_ym.setIcon(icon16)
        self.pbtn_inside_ym.setIconSize(QSize(48, 48))
        self.pbtn_inside_ym.setCheckable(False)
        self.pbtn_inside_ym.setChecked(False)
        self.pbtn_inside_ym.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_ym, 2, 1, 1, 1)

        self.pbtn_inside_xpym = PushButton(self.widget_inside_btns)
        self.inside_buttonGroup.addButton(self.pbtn_inside_xpym)
        self.pbtn_inside_xpym.setObjectName(u"pbtn_inside_xpym")
        sizePolicy.setHeightForWidth(self.pbtn_inside_xpym.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_xpym.setSizePolicy(sizePolicy)
        self.pbtn_inside_xpym.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_xpym.setMaximumSize(QSize(50, 50))
        icon17 = QIcon()
        icon17.addFile(u"../images/probe_icons/inX+Y-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_xpym.setIcon(icon17)
        self.pbtn_inside_xpym.setIconSize(QSize(48, 48))
        self.pbtn_inside_xpym.setCheckable(False)
        self.pbtn_inside_xpym.setChecked(False)
        self.pbtn_inside_xpym.setProperty("indicator_option", False)

        self.gridLayout.addWidget(self.pbtn_inside_xpym, 2, 2, 1, 1)


        self.verticalLayout.addWidget(self.widget_inside_btns)

        self.widget_buttons = QWidget(self.widget_inside_measure)
        self.widget_buttons.setObjectName(u"widget_buttons")
        sizePolicy.setHeightForWidth(self.widget_buttons.sizePolicy().hasHeightForWidth())
        self.widget_buttons.setSizePolicy(sizePolicy)
        self.widget_buttons.setMinimumSize(QSize(160, 0))
        self.widget_buttons.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_10 = QVBoxLayout(self.widget_buttons)
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.widget_auto = QWidget(self.widget_buttons)
        self.widget_auto.setObjectName(u"widget_auto")
        self.horizontalLayout_29 = QHBoxLayout(self.widget_auto)
        self.horizontalLayout_29.setSpacing(4)
        self.horizontalLayout_29.setObjectName(u"horizontalLayout_29")
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.allow_auto_zero = PushButton(self.widget_auto)
        self.allow_auto_zero.setObjectName(u"allow_auto_zero")
        sizePolicy.setHeightForWidth(self.allow_auto_zero.sizePolicy().hasHeightForWidth())
        self.allow_auto_zero.setSizePolicy(sizePolicy)
        self.allow_auto_zero.setMinimumSize(QSize(80, 50))
        self.allow_auto_zero.setMaximumSize(QSize(80, 50))
        self.allow_auto_zero.setCheckable(True)
        self.allow_auto_zero.setChecked(False)
        self.allow_auto_zero.setProperty("indicator_option", False)
        self.allow_auto_zero.setProperty("indicator_HAL_pin_option", False)
        self.allow_auto_zero.setProperty("indicator_status_option", False)
        self.allow_auto_zero.setProperty("on_color", QColor(255, 255, 0))
        self.allow_auto_zero.setProperty("indicator_size", 0.200000000000000)

        self.horizontalLayout_29.addWidget(self.allow_auto_zero)

        self.allow_auto_skew = PushButton(self.widget_auto)
        self.allow_auto_skew.setObjectName(u"allow_auto_skew")
        sizePolicy.setHeightForWidth(self.allow_auto_skew.sizePolicy().hasHeightForWidth())
        self.allow_auto_skew.setSizePolicy(sizePolicy)
        self.allow_auto_skew.setMinimumSize(QSize(80, 50))
        self.allow_auto_skew.setMaximumSize(QSize(80, 50))
        self.allow_auto_skew.setCheckable(True)
        self.allow_auto_skew.setChecked(False)
        self.allow_auto_skew.setProperty("indicator_option", False)
        self.allow_auto_skew.setProperty("on_color", QColor(255, 255, 0))
        self.allow_auto_skew.setProperty("indicator_size", 0.200000000000000)

        self.horizontalLayout_29.addWidget(self.allow_auto_skew)


        self.verticalLayout_10.addWidget(self.widget_auto)

        self.widget_set_angle = QWidget(self.widget_buttons)
        self.widget_set_angle.setObjectName(u"widget_set_angle")
        self.horizontalLayout_30 = QHBoxLayout(self.widget_set_angle)
        self.horizontalLayout_30.setSpacing(4)
        self.horizontalLayout_30.setObjectName(u"horizontalLayout_30")
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.pbtn_set_angle = PushButton(self.widget_set_angle)
        self.pbtn_set_angle.setObjectName(u"pbtn_set_angle")
        sizePolicy.setHeightForWidth(self.pbtn_set_angle.sizePolicy().hasHeightForWidth())
        self.pbtn_set_angle.setSizePolicy(sizePolicy)
        self.pbtn_set_angle.setMinimumSize(QSize(80, 50))
        self.pbtn_set_angle.setMaximumSize(QSize(80, 50))
        self.pbtn_set_angle.setCheckable(False)
        self.pbtn_set_angle.setChecked(False)
        self.pbtn_set_angle.setProperty("indicator_option", False)

        self.horizontalLayout_30.addWidget(self.pbtn_set_angle)

        self.pbtn_use_tool_measurement = PushButton(self.widget_set_angle)
        self.pbtn_use_tool_measurement.setObjectName(u"pbtn_use_tool_measurement")
        self.pbtn_use_tool_measurement.setEnabled(True)
        sizePolicy.setHeightForWidth(self.pbtn_use_tool_measurement.sizePolicy().hasHeightForWidth())
        self.pbtn_use_tool_measurement.setSizePolicy(sizePolicy)
        self.pbtn_use_tool_measurement.setMinimumSize(QSize(80, 50))
        self.pbtn_use_tool_measurement.setMaximumSize(QSize(80, 50))
        font3 = QFont()
        font3.setFamily(u"DejaVu Sans")
        font3.setPointSize(10)
        self.pbtn_use_tool_measurement.setFont(font3)
        self.pbtn_use_tool_measurement.setCheckable(True)
        self.pbtn_use_tool_measurement.setProperty("indicator_option", True)
        self.pbtn_use_tool_measurement.setProperty("on_color", QColor(0, 255, 0))
        self.pbtn_use_tool_measurement.setProperty("indicator_size", 0.200000000000000)

        self.horizontalLayout_30.addWidget(self.pbtn_use_tool_measurement)


        self.verticalLayout_10.addWidget(self.widget_set_angle)


        self.verticalLayout.addWidget(self.widget_buttons)


        self.horizontalLayout_14.addWidget(self.widget_inside_measure)

        self.widget_skew_measure = QWidget(self.widget_top)
        self.widget_skew_measure.setObjectName(u"widget_skew_measure")
        self.widget_skew_measure.setMinimumSize(QSize(150, 0))
        self.widget_skew_measure.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_3 = QVBoxLayout(self.widget_skew_measure)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_skewed_label = QLabel(self.widget_skew_measure)
        self.label_skewed_label.setObjectName(u"label_skewed_label")
        sizePolicy1.setHeightForWidth(self.label_skewed_label.sizePolicy().hasHeightForWidth())
        self.label_skewed_label.setSizePolicy(sizePolicy1)
        self.label_skewed_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_skewed_label)

        self.widget_skew = QWidget(self.widget_skew_measure)
        self.widget_skew.setObjectName(u"widget_skew")
        sizePolicy.setHeightForWidth(self.widget_skew.sizePolicy().hasHeightForWidth())
        self.widget_skew.setSizePolicy(sizePolicy)
        self.widget_skew.setMinimumSize(QSize(0, 0))
        self.widget_skew.setMaximumSize(QSize(16777215, 16777215))
        self.gridLayout_2 = QGridLayout(self.widget_skew)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pbtn_outside_length_x = PushButton(self.widget_skew)
        self.length_buttonGroup = QButtonGroup(versaProbe)
        self.length_buttonGroup.setObjectName(u"length_buttonGroup")
        self.length_buttonGroup.setExclusive(False)
        self.length_buttonGroup.addButton(self.pbtn_outside_length_x)
        self.pbtn_outside_length_x.setObjectName(u"pbtn_outside_length_x")
        sizePolicy.setHeightForWidth(self.pbtn_outside_length_x.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_length_x.setSizePolicy(sizePolicy)
        self.pbtn_outside_length_x.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_length_x.setMaximumSize(QSize(60, 50))
        icon18 = QIcon()
        icon18.addFile(u"../images/probe_icons/outside_xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_length_x.setIcon(icon18)
        self.pbtn_outside_length_x.setIconSize(QSize(48, 48))
        self.pbtn_outside_length_x.setCheckable(False)
        self.pbtn_outside_length_x.setChecked(False)
        self.pbtn_outside_length_x.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_outside_length_x, 3, 1, 1, 1)

        self.pbtn_inside_length_x = PushButton(self.widget_skew)
        self.length_buttonGroup.addButton(self.pbtn_inside_length_x)
        self.pbtn_inside_length_x.setObjectName(u"pbtn_inside_length_x")
        sizePolicy.setHeightForWidth(self.pbtn_inside_length_x.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_length_x.setSizePolicy(sizePolicy)
        self.pbtn_inside_length_x.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_length_x.setMaximumSize(QSize(60, 50))
        icon19 = QIcon()
        icon19.addFile(u"../images/probe_icons/inside_xl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_length_x.setIcon(icon19)
        self.pbtn_inside_length_x.setIconSize(QSize(48, 48))
        self.pbtn_inside_length_x.setCheckable(False)
        self.pbtn_inside_length_x.setChecked(False)
        self.pbtn_inside_length_x.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_inside_length_x, 3, 0, 1, 1)

        self.pbtn_skew_xp = PushButton(self.widget_skew)
        self.skew_buttonGroup = QButtonGroup(versaProbe)
        self.skew_buttonGroup.setObjectName(u"skew_buttonGroup")
        self.skew_buttonGroup.setExclusive(False)
        self.skew_buttonGroup.addButton(self.pbtn_skew_xp)
        self.pbtn_skew_xp.setObjectName(u"pbtn_skew_xp")
        sizePolicy.setHeightForWidth(self.pbtn_skew_xp.sizePolicy().hasHeightForWidth())
        self.pbtn_skew_xp.setSizePolicy(sizePolicy)
        self.pbtn_skew_xp.setMinimumSize(QSize(50, 50))
        self.pbtn_skew_xp.setMaximumSize(QSize(60, 50))
        icon20 = QIcon()
        icon20.addFile(u"../images/probe_icons/angleX+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_skew_xp.setIcon(icon20)
        self.pbtn_skew_xp.setIconSize(QSize(48, 48))
        self.pbtn_skew_xp.setCheckable(False)
        self.pbtn_skew_xp.setChecked(False)
        self.pbtn_skew_xp.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_skew_xp, 0, 0, 1, 1)

        self.pbtn_skew_yp = PushButton(self.widget_skew)
        self.skew_buttonGroup.addButton(self.pbtn_skew_yp)
        self.pbtn_skew_yp.setObjectName(u"pbtn_skew_yp")
        sizePolicy.setHeightForWidth(self.pbtn_skew_yp.sizePolicy().hasHeightForWidth())
        self.pbtn_skew_yp.setSizePolicy(sizePolicy)
        self.pbtn_skew_yp.setMinimumSize(QSize(50, 50))
        self.pbtn_skew_yp.setMaximumSize(QSize(60, 50))
        icon21 = QIcon()
        icon21.addFile(u"../images/probe_icons/angleY+.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_skew_yp.setIcon(icon21)
        self.pbtn_skew_yp.setIconSize(QSize(48, 48))
        self.pbtn_skew_yp.setCheckable(False)
        self.pbtn_skew_yp.setChecked(False)
        self.pbtn_skew_yp.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_skew_yp, 1, 0, 1, 1)

        self.pbtn_skew_ym = PushButton(self.widget_skew)
        self.skew_buttonGroup.addButton(self.pbtn_skew_ym)
        self.pbtn_skew_ym.setObjectName(u"pbtn_skew_ym")
        sizePolicy.setHeightForWidth(self.pbtn_skew_ym.sizePolicy().hasHeightForWidth())
        self.pbtn_skew_ym.setSizePolicy(sizePolicy)
        self.pbtn_skew_ym.setMinimumSize(QSize(50, 50))
        self.pbtn_skew_ym.setMaximumSize(QSize(60, 50))
        icon22 = QIcon()
        icon22.addFile(u"../images/probe_icons/angleY-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_skew_ym.setIcon(icon22)
        self.pbtn_skew_ym.setIconSize(QSize(48, 48))
        self.pbtn_skew_ym.setCheckable(False)
        self.pbtn_skew_ym.setChecked(False)
        self.pbtn_skew_ym.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_skew_ym, 0, 1, 1, 1)

        self.pbtn_skew_xm = PushButton(self.widget_skew)
        self.skew_buttonGroup.addButton(self.pbtn_skew_xm)
        self.pbtn_skew_xm.setObjectName(u"pbtn_skew_xm")
        sizePolicy.setHeightForWidth(self.pbtn_skew_xm.sizePolicy().hasHeightForWidth())
        self.pbtn_skew_xm.setSizePolicy(sizePolicy)
        self.pbtn_skew_xm.setMinimumSize(QSize(50, 50))
        self.pbtn_skew_xm.setMaximumSize(QSize(60, 50))
        icon23 = QIcon()
        icon23.addFile(u"../images/probe_icons/angleX-.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_skew_xm.setIcon(icon23)
        self.pbtn_skew_xm.setIconSize(QSize(48, 48))
        self.pbtn_skew_xm.setCheckable(False)
        self.pbtn_skew_xm.setChecked(False)
        self.pbtn_skew_xm.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_skew_xm, 1, 1, 1, 1)

        self.pbtn_measure_diam = PushButton(self.widget_skew)
        self.pbtn_measure_diam.setObjectName(u"pbtn_measure_diam")
        self.pbtn_measure_diam.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pbtn_measure_diam.sizePolicy().hasHeightForWidth())
        self.pbtn_measure_diam.setSizePolicy(sizePolicy)
        self.pbtn_measure_diam.setMinimumSize(QSize(50, 50))
        self.pbtn_measure_diam.setMaximumSize(QSize(60, 50))
        icon24 = QIcon()
        icon24.addFile(u"../images/probe_icons/tool_dia.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_measure_diam.setIcon(icon24)
        self.pbtn_measure_diam.setIconSize(QSize(48, 48))
        self.pbtn_measure_diam.setCheckable(False)
        self.pbtn_measure_diam.setChecked(False)
        self.pbtn_measure_diam.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_measure_diam, 5, 1, 1, 1)

        self.pbtn_inside_length_y = PushButton(self.widget_skew)
        self.length_buttonGroup.addButton(self.pbtn_inside_length_y)
        self.pbtn_inside_length_y.setObjectName(u"pbtn_inside_length_y")
        sizePolicy.setHeightForWidth(self.pbtn_inside_length_y.sizePolicy().hasHeightForWidth())
        self.pbtn_inside_length_y.setSizePolicy(sizePolicy)
        self.pbtn_inside_length_y.setMinimumSize(QSize(50, 50))
        self.pbtn_inside_length_y.setMaximumSize(QSize(60, 50))
        icon25 = QIcon()
        icon25.addFile(u"../images/probe_icons/inside_yl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_inside_length_y.setIcon(icon25)
        self.pbtn_inside_length_y.setIconSize(QSize(48, 48))
        self.pbtn_inside_length_y.setCheckable(False)
        self.pbtn_inside_length_y.setChecked(False)
        self.pbtn_inside_length_y.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_inside_length_y, 4, 0, 1, 1)

        self.pbtn_down = PushButton(self.widget_skew)
        self.length_buttonGroup.addButton(self.pbtn_down)
        self.pbtn_down.setObjectName(u"pbtn_down")
        sizePolicy.setHeightForWidth(self.pbtn_down.sizePolicy().hasHeightForWidth())
        self.pbtn_down.setSizePolicy(sizePolicy)
        self.pbtn_down.setMinimumSize(QSize(50, 50))
        self.pbtn_down.setMaximumSize(QSize(60, 50))
        icon26 = QIcon()
        icon26.addFile(u"../images/probe_icons/down.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_down.setIcon(icon26)
        self.pbtn_down.setIconSize(QSize(48, 48))
        self.pbtn_down.setCheckable(False)
        self.pbtn_down.setChecked(False)
        self.pbtn_down.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_down, 5, 0, 1, 1)

        self.pbtn_outside_length_y = PushButton(self.widget_skew)
        self.length_buttonGroup.addButton(self.pbtn_outside_length_y)
        self.pbtn_outside_length_y.setObjectName(u"pbtn_outside_length_y")
        sizePolicy.setHeightForWidth(self.pbtn_outside_length_y.sizePolicy().hasHeightForWidth())
        self.pbtn_outside_length_y.setSizePolicy(sizePolicy)
        self.pbtn_outside_length_y.setMinimumSize(QSize(50, 50))
        self.pbtn_outside_length_y.setMaximumSize(QSize(60, 50))
        icon27 = QIcon()
        icon27.addFile(u"../images/probe_icons/outside_yl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbtn_outside_length_y.setIcon(icon27)
        self.pbtn_outside_length_y.setIconSize(QSize(48, 48))
        self.pbtn_outside_length_y.setCheckable(False)
        self.pbtn_outside_length_y.setChecked(False)
        self.pbtn_outside_length_y.setProperty("indicator_option", False)

        self.gridLayout_2.addWidget(self.pbtn_outside_length_y, 4, 1, 1, 1)

        self.lbl_lengths = QLabel(self.widget_skew)
        self.lbl_lengths.setObjectName(u"lbl_lengths")
        self.lbl_lengths.setMinimumSize(QSize(0, 24))
        self.lbl_lengths.setMaximumSize(QSize(16777215, 24))
        self.lbl_lengths.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.lbl_lengths, 2, 0, 1, 2)


        self.verticalLayout_3.addWidget(self.widget_skew)


        self.horizontalLayout_14.addWidget(self.widget_skew_measure)

        self.widget_results = QWidget(self.widget_top)
        self.widget_results.setObjectName(u"widget_results")
        self.widget_results.setMinimumSize(QSize(140, 0))
        self.verticalLayout_4 = QVBoxLayout(self.widget_results)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.lbl_results = QLabel(self.widget_results)
        self.lbl_results.setObjectName(u"lbl_results")
        self.lbl_results.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.lbl_results)

        self.horizontalWidget = QWidget(self.widget_results)
        self.horizontalWidget.setObjectName(u"horizontalWidget")
        sizePolicy1.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy1)
        self.horizontalWidget.setMinimumSize(QSize(0, 0))
        self.horizontalWidget.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.lab_xn = QLabel(self.horizontalWidget)
        self.lab_xn.setObjectName(u"lab_xn")
        sizePolicy.setHeightForWidth(self.lab_xn.sizePolicy().hasHeightForWidth())
        self.lab_xn.setSizePolicy(sizePolicy)
        self.lab_xn.setMinimumSize(QSize(0, 24))
        self.lab_xn.setMaximumSize(QSize(16777215, 24))
        self.lab_xn.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_2.addWidget(self.lab_xn)

        self.status_xm = QLineEdit(self.horizontalWidget)
        self.status_xm.setObjectName(u"status_xm")
        self.status_xm.setEnabled(True)
        sizePolicy.setHeightForWidth(self.status_xm.sizePolicy().hasHeightForWidth())
        self.status_xm.setSizePolicy(sizePolicy)
        self.status_xm.setMinimumSize(QSize(70, 24))
        self.status_xm.setMaximumSize(QSize(70, 16777215))
        self.status_xm.setMaxLength(10)
        self.status_xm.setAlignment(Qt.AlignCenter)
        self.status_xm.setReadOnly(True)

        self.horizontalLayout_2.addWidget(self.status_xm)


        self.verticalLayout_4.addWidget(self.horizontalWidget)

        self.horizontalWidget_2 = QWidget(self.widget_results)
        self.horizontalWidget_2.setObjectName(u"horizontalWidget_2")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy1)
        self.horizontalWidget_2.setMinimumSize(QSize(0, 0))
        self.horizontalWidget_2.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.lab_xc = QLabel(self.horizontalWidget_2)
        self.lab_xc.setObjectName(u"lab_xc")
        self.lab_xc.setMinimumSize(QSize(0, 24))
        self.lab_xc.setMaximumSize(QSize(16777215, 24))
        self.lab_xc.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_3.addWidget(self.lab_xc)

        self.status_xc = QLineEdit(self.horizontalWidget_2)
        self.status_xc.setObjectName(u"status_xc")
        sizePolicy.setHeightForWidth(self.status_xc.sizePolicy().hasHeightForWidth())
        self.status_xc.setSizePolicy(sizePolicy)
        self.status_xc.setMinimumSize(QSize(70, 24))
        self.status_xc.setMaximumSize(QSize(70, 24))
        self.status_xc.setMaxLength(10)
        self.status_xc.setAlignment(Qt.AlignCenter)
        self.status_xc.setReadOnly(True)

        self.horizontalLayout_3.addWidget(self.status_xc)


        self.verticalLayout_4.addWidget(self.horizontalWidget_2)

        self.horizontalWidget_3 = QWidget(self.widget_results)
        self.horizontalWidget_3.setObjectName(u"horizontalWidget_3")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_3.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_3.setSizePolicy(sizePolicy1)
        self.horizontalWidget_3.setMinimumSize(QSize(0, 0))
        self.horizontalWidget_3.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.lab_xp = QLabel(self.horizontalWidget_3)
        self.lab_xp.setObjectName(u"lab_xp")
        self.lab_xp.setMinimumSize(QSize(0, 24))
        self.lab_xp.setMaximumSize(QSize(16777215, 24))
        self.lab_xp.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_4.addWidget(self.lab_xp)

        self.status_xp = QLineEdit(self.horizontalWidget_3)
        self.status_xp.setObjectName(u"status_xp")
        sizePolicy.setHeightForWidth(self.status_xp.sizePolicy().hasHeightForWidth())
        self.status_xp.setSizePolicy(sizePolicy)
        self.status_xp.setMinimumSize(QSize(70, 24))
        self.status_xp.setMaximumSize(QSize(70, 24))
        self.status_xp.setMaxLength(10)
        self.status_xp.setAlignment(Qt.AlignCenter)
        self.status_xp.setReadOnly(True)

        self.horizontalLayout_4.addWidget(self.status_xp)


        self.verticalLayout_4.addWidget(self.horizontalWidget_3)

        self.horizontalWidget_4 = QWidget(self.widget_results)
        self.horizontalWidget_4.setObjectName(u"horizontalWidget_4")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_4.setSizePolicy(sizePolicy1)
        self.horizontalWidget_4.setMinimumSize(QSize(0, 0))
        self.horizontalWidget_4.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.lab_lx = QLabel(self.horizontalWidget_4)
        self.lab_lx.setObjectName(u"lab_lx")
        self.lab_lx.setMinimumSize(QSize(0, 24))
        self.lab_lx.setMaximumSize(QSize(16777215, 24))
        self.lab_lx.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_5.addWidget(self.lab_lx)

        self.status_lx = QLineEdit(self.horizontalWidget_4)
        self.status_lx.setObjectName(u"status_lx")
        sizePolicy.setHeightForWidth(self.status_lx.sizePolicy().hasHeightForWidth())
        self.status_lx.setSizePolicy(sizePolicy)
        self.status_lx.setMinimumSize(QSize(70, 24))
        self.status_lx.setMaximumSize(QSize(70, 24))
        self.status_lx.setMaxLength(10)
        self.status_lx.setAlignment(Qt.AlignCenter)
        self.status_lx.setReadOnly(True)

        self.horizontalLayout_5.addWidget(self.status_lx)


        self.verticalLayout_4.addWidget(self.horizontalWidget_4)

        self.horizontalWidget_5 = QWidget(self.widget_results)
        self.horizontalWidget_5.setObjectName(u"horizontalWidget_5")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_5.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_5.setSizePolicy(sizePolicy1)
        self.horizontalWidget_5.setMinimumSize(QSize(0, 0))
        self.horizontalWidget_5.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalWidget_5)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.lab_yn = QLabel(self.horizontalWidget_5)
        self.lab_yn.setObjectName(u"lab_yn")
        self.lab_yn.setMinimumSize(QSize(0, 24))
        self.lab_yn.setMaximumSize(QSize(16777215, 24))
        self.lab_yn.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_6.addWidget(self.lab_yn)

        self.status_ym = QLineEdit(self.horizontalWidget_5)
        self.status_ym.setObjectName(u"status_ym")
        sizePolicy.setHeightForWidth(self.status_ym.sizePolicy().hasHeightForWidth())
        self.status_ym.setSizePolicy(sizePolicy)
        self.status_ym.setMinimumSize(QSize(70, 25))
        self.status_ym.setMaximumSize(QSize(70, 24))
        self.status_ym.setMaxLength(10)
        self.status_ym.setAlignment(Qt.AlignCenter)
        self.status_ym.setReadOnly(True)

        self.horizontalLayout_6.addWidget(self.status_ym)


        self.verticalLayout_4.addWidget(self.horizontalWidget_5)

        self.horizontalWidget_6 = QWidget(self.widget_results)
        self.horizontalWidget_6.setObjectName(u"horizontalWidget_6")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_6.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_6.setSizePolicy(sizePolicy1)
        self.horizontalWidget_6.setMinimumSize(QSize(0, 0))
        self.horizontalWidget_6.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalWidget_6)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.lab_yc = QLabel(self.horizontalWidget_6)
        self.lab_yc.setObjectName(u"lab_yc")
        self.lab_yc.setMinimumSize(QSize(0, 24))
        self.lab_yc.setMaximumSize(QSize(16777215, 24))
        self.lab_yc.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_7.addWidget(self.lab_yc)

        self.status_yc = QLineEdit(self.horizontalWidget_6)
        self.status_yc.setObjectName(u"status_yc")
        sizePolicy.setHeightForWidth(self.status_yc.sizePolicy().hasHeightForWidth())
        self.status_yc.setSizePolicy(sizePolicy)
        self.status_yc.setMinimumSize(QSize(70, 25))
        self.status_yc.setMaximumSize(QSize(70, 24))
        self.status_yc.setMaxLength(10)
        self.status_yc.setAlignment(Qt.AlignCenter)
        self.status_yc.setReadOnly(True)

        self.horizontalLayout_7.addWidget(self.status_yc)


        self.verticalLayout_4.addWidget(self.horizontalWidget_6)

        self.horizontalWidget_7 = QWidget(self.widget_results)
        self.horizontalWidget_7.setObjectName(u"horizontalWidget_7")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_7.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_7.setSizePolicy(sizePolicy1)
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalWidget_7)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.lab_yp = QLabel(self.horizontalWidget_7)
        self.lab_yp.setObjectName(u"lab_yp")
        self.lab_yp.setMinimumSize(QSize(0, 24))
        self.lab_yp.setMaximumSize(QSize(16777215, 24))
        self.lab_yp.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_8.addWidget(self.lab_yp)

        self.status_yp = QLineEdit(self.horizontalWidget_7)
        self.status_yp.setObjectName(u"status_yp")
        sizePolicy.setHeightForWidth(self.status_yp.sizePolicy().hasHeightForWidth())
        self.status_yp.setSizePolicy(sizePolicy)
        self.status_yp.setMinimumSize(QSize(70, 25))
        self.status_yp.setMaximumSize(QSize(70, 24))
        self.status_yp.setMaxLength(10)
        self.status_yp.setAlignment(Qt.AlignCenter)
        self.status_yp.setReadOnly(True)

        self.horizontalLayout_8.addWidget(self.status_yp)


        self.verticalLayout_4.addWidget(self.horizontalWidget_7)

        self.horizontalWidget_8 = QWidget(self.widget_results)
        self.horizontalWidget_8.setObjectName(u"horizontalWidget_8")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_8.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_8.setSizePolicy(sizePolicy1)
        self.horizontalLayout_9 = QHBoxLayout(self.horizontalWidget_8)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.lab_ly = QLabel(self.horizontalWidget_8)
        self.lab_ly.setObjectName(u"lab_ly")
        self.lab_ly.setMinimumSize(QSize(0, 24))
        self.lab_ly.setMaximumSize(QSize(16777215, 24))
        self.lab_ly.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_9.addWidget(self.lab_ly)

        self.status_ly = QLineEdit(self.horizontalWidget_8)
        self.status_ly.setObjectName(u"status_ly")
        sizePolicy.setHeightForWidth(self.status_ly.sizePolicy().hasHeightForWidth())
        self.status_ly.setSizePolicy(sizePolicy)
        self.status_ly.setMinimumSize(QSize(70, 25))
        self.status_ly.setMaximumSize(QSize(70, 24))
        self.status_ly.setMaxLength(10)
        self.status_ly.setAlignment(Qt.AlignCenter)
        self.status_ly.setReadOnly(True)

        self.horizontalLayout_9.addWidget(self.status_ly)


        self.verticalLayout_4.addWidget(self.horizontalWidget_8)

        self.horizontalWidget_10 = QWidget(self.widget_results)
        self.horizontalWidget_10.setObjectName(u"horizontalWidget_10")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_10.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_10.setSizePolicy(sizePolicy1)
        self.horizontalLayout_11 = QHBoxLayout(self.horizontalWidget_10)
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.lab_z = QLabel(self.horizontalWidget_10)
        self.lab_z.setObjectName(u"lab_z")
        self.lab_z.setMinimumSize(QSize(0, 24))
        self.lab_z.setMaximumSize(QSize(16777215, 24))
        self.lab_z.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_11.addWidget(self.lab_z)

        self.status_z = QLineEdit(self.horizontalWidget_10)
        self.status_z.setObjectName(u"status_z")
        sizePolicy.setHeightForWidth(self.status_z.sizePolicy().hasHeightForWidth())
        self.status_z.setSizePolicy(sizePolicy)
        self.status_z.setMinimumSize(QSize(70, 25))
        self.status_z.setMaximumSize(QSize(70, 24))
        self.status_z.setMaxLength(10)
        self.status_z.setAlignment(Qt.AlignCenter)
        self.status_z.setReadOnly(True)

        self.horizontalLayout_11.addWidget(self.status_z)


        self.verticalLayout_4.addWidget(self.horizontalWidget_10)

        self.horizontalWidget1 = QWidget(self.widget_results)
        self.horizontalWidget1.setObjectName(u"horizontalWidget1")
        sizePolicy1.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy1)
        self.horizontalLayout_12 = QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.lab_diam = QLabel(self.horizontalWidget1)
        self.lab_diam.setObjectName(u"lab_diam")
        self.lab_diam.setMinimumSize(QSize(0, 24))
        self.lab_diam.setMaximumSize(QSize(16777215, 24))
        self.lab_diam.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_12.addWidget(self.lab_diam)

        self.status_d = QLineEdit(self.horizontalWidget1)
        self.status_d.setObjectName(u"status_d")
        sizePolicy.setHeightForWidth(self.status_d.sizePolicy().hasHeightForWidth())
        self.status_d.setSizePolicy(sizePolicy)
        self.status_d.setMinimumSize(QSize(70, 25))
        self.status_d.setMaximumSize(QSize(70, 24))
        self.status_d.setMaxLength(10)
        self.status_d.setAlignment(Qt.AlignCenter)
        self.status_d.setReadOnly(True)

        self.horizontalLayout_12.addWidget(self.status_d)


        self.verticalLayout_4.addWidget(self.horizontalWidget1)

        self.horizontalWidget2 = QWidget(self.widget_results)
        self.horizontalWidget2.setObjectName(u"horizontalWidget2")
        sizePolicy1.setHeightForWidth(self.horizontalWidget2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget2.setSizePolicy(sizePolicy1)
        self.horizontalLayout_13 = QHBoxLayout(self.horizontalWidget2)
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.lab_ang = QLabel(self.horizontalWidget2)
        self.lab_ang.setObjectName(u"lab_ang")
        self.lab_ang.setMinimumSize(QSize(0, 24))
        self.lab_ang.setMaximumSize(QSize(16777215, 24))
        self.lab_ang.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_13.addWidget(self.lab_ang)

        self.status_a = QLineEdit(self.horizontalWidget2)
        self.status_a.setObjectName(u"status_a")
        sizePolicy.setHeightForWidth(self.status_a.sizePolicy().hasHeightForWidth())
        self.status_a.setSizePolicy(sizePolicy)
        self.status_a.setMinimumSize(QSize(70, 25))
        self.status_a.setMaximumSize(QSize(70, 24))
        self.status_a.setMaxLength(10)
        self.status_a.setAlignment(Qt.AlignCenter)
        self.status_a.setReadOnly(True)

        self.horizontalLayout_13.addWidget(self.status_a)


        self.verticalLayout_4.addWidget(self.horizontalWidget2)


        self.horizontalLayout_14.addWidget(self.widget_results)


        self.verticalLayout_8.addWidget(self.widget_top)

        self.widget_settings = QWidget(self.widget_probing)
        self.widget_settings.setObjectName(u"widget_settings")
        self.gridLayout_5 = QGridLayout(self.widget_settings)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.lab_probe_vel = QLabel(self.widget_settings)
        self.lab_probe_vel.setObjectName(u"lab_probe_vel")
        self.lab_probe_vel.setAlignment(Qt.AlignCenter)
        self.lab_probe_vel.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_probe_vel, 5, 2, 1, 1)

        self.input_side_edge_length = QLineEdit(self.widget_settings)
        self.input_side_edge_length.setObjectName(u"input_side_edge_length")
        sizePolicy.setHeightForWidth(self.input_side_edge_length.sizePolicy().hasHeightForWidth())
        self.input_side_edge_length.setSizePolicy(sizePolicy)
        self.input_side_edge_length.setMinimumSize(QSize(80, 24))
        self.input_side_edge_length.setMaximumSize(QSize(80, 24))
        self.input_side_edge_length.setFont(font2)
        self.input_side_edge_length.setCursor(QCursor(Qt.IBeamCursor))
        self.input_side_edge_length.setMaxLength(7)
        self.input_side_edge_length.setFrame(True)
        self.input_side_edge_length.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_side_edge_length, 3, 5, 1, 1)

        self.lab_latch_rtrn_dist = QLabel(self.widget_settings)
        self.lab_latch_rtrn_dist.setObjectName(u"lab_latch_rtrn_dist")
        self.lab_latch_rtrn_dist.setAlignment(Qt.AlignCenter)
        self.lab_latch_rtrn_dist.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_latch_rtrn_dist, 5, 0, 1, 1)

        self.lab_ball_diam = QLabel(self.widget_settings)
        self.lab_ball_diam.setObjectName(u"lab_ball_diam")
        self.lab_ball_diam.setAlignment(Qt.AlignCenter)
        self.lab_ball_diam.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_ball_diam, 3, 0, 1, 1)

        self.input_probe_diam = QLineEdit(self.widget_settings)
        self.input_probe_diam.setObjectName(u"input_probe_diam")
        sizePolicy.setHeightForWidth(self.input_probe_diam.sizePolicy().hasHeightForWidth())
        self.input_probe_diam.setSizePolicy(sizePolicy)
        self.input_probe_diam.setMinimumSize(QSize(80, 24))
        self.input_probe_diam.setMaximumSize(QSize(80, 24))
        self.input_probe_diam.setFont(font2)
        self.input_probe_diam.setCursor(QCursor(Qt.IBeamCursor))
        self.input_probe_diam.setMouseTracking(True)
        self.input_probe_diam.setLayoutDirection(Qt.LeftToRight)
        self.input_probe_diam.setMaxLength(5)
        self.input_probe_diam.setFrame(True)
        self.input_probe_diam.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_probe_diam, 3, 1, 1, 1)

        self.input_latch_return_dist = QLineEdit(self.widget_settings)
        self.input_latch_return_dist.setObjectName(u"input_latch_return_dist")
        sizePolicy.setHeightForWidth(self.input_latch_return_dist.sizePolicy().hasHeightForWidth())
        self.input_latch_return_dist.setSizePolicy(sizePolicy)
        self.input_latch_return_dist.setMinimumSize(QSize(80, 24))
        self.input_latch_return_dist.setMaximumSize(QSize(80, 24))
        self.input_latch_return_dist.setFont(font2)
        self.input_latch_return_dist.setCursor(QCursor(Qt.IBeamCursor))
        self.input_latch_return_dist.setMaxLength(7)
        self.input_latch_return_dist.setFrame(True)
        self.input_latch_return_dist.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_latch_return_dist, 5, 1, 1, 1)

        self.lab_xy = QLabel(self.widget_settings)
        self.lab_xy.setObjectName(u"lab_xy")
        self.lab_xy.setAlignment(Qt.AlignCenter)
        self.lab_xy.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_xy, 3, 6, 1, 1)

        self.label_tool_block_height_2 = QLabel(self.widget_settings)
        self.label_tool_block_height_2.setObjectName(u"label_tool_block_height_2")
        self.label_tool_block_height_2.setAlignment(Qt.AlignCenter)
        self.label_tool_block_height_2.setMargin(4)

        self.gridLayout_5.addWidget(self.label_tool_block_height_2, 5, 4, 1, 1)

        self.input_tool_block_height = QLineEdit(self.widget_settings)
        self.input_tool_block_height.setObjectName(u"input_tool_block_height")
        sizePolicy.setHeightForWidth(self.input_tool_block_height.sizePolicy().hasHeightForWidth())
        self.input_tool_block_height.setSizePolicy(sizePolicy)
        self.input_tool_block_height.setMinimumSize(QSize(80, 24))
        self.input_tool_block_height.setMaximumSize(QSize(80, 24))
        self.input_tool_block_height.setFont(font2)
        self.input_tool_block_height.setCursor(QCursor(Qt.IBeamCursor))
        self.input_tool_block_height.setMaxLength(7)
        self.input_tool_block_height.setFrame(True)
        self.input_tool_block_height.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_tool_block_height, 5, 5, 1, 1)

        self.led_probe_function_chk = LED(self.widget_settings)
        self.led_probe_function_chk.setObjectName(u"led_probe_function_chk")
        self.led_probe_function_chk.setColor(QColor(0, 255, 0))

        self.gridLayout_5.addWidget(self.led_probe_function_chk, 0, 0, 1, 1)

        self.lab_side_edge = QLabel(self.widget_settings)
        self.lab_side_edge.setObjectName(u"lab_side_edge")
        self.lab_side_edge.setMinimumSize(QSize(0, 24))
        self.lab_side_edge.setMaximumSize(QSize(16777215, 24))
        self.lab_side_edge.setFont(font1)
        self.lab_side_edge.setFrameShape(QFrame.NoFrame)
        self.lab_side_edge.setFrameShadow(QFrame.Plain)
        self.lab_side_edge.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.lab_side_edge, 0, 5, 1, 1)

        self.input_max_travel = QLineEdit(self.widget_settings)
        self.input_max_travel.setObjectName(u"input_max_travel")
        sizePolicy.setHeightForWidth(self.input_max_travel.sizePolicy().hasHeightForWidth())
        self.input_max_travel.setSizePolicy(sizePolicy)
        self.input_max_travel.setMinimumSize(QSize(80, 24))
        self.input_max_travel.setMaximumSize(QSize(80, 24))
        self.input_max_travel.setFont(font2)
        self.input_max_travel.setCursor(QCursor(Qt.IBeamCursor))
        self.input_max_travel.setMaxLength(7)
        self.input_max_travel.setFrame(True)
        self.input_max_travel.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_max_travel, 4, 1, 1, 1)

        self.lab_probe = QLabel(self.widget_settings)
        self.lab_probe.setObjectName(u"lab_probe")
        self.lab_probe.setMinimumSize(QSize(0, 24))
        self.lab_probe.setMaximumSize(QSize(16777215, 24))
        self.lab_probe.setFont(font1)
        self.lab_probe.setFrameShape(QFrame.NoFrame)
        self.lab_probe.setFrameShadow(QFrame.Plain)
        self.lab_probe.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.lab_probe, 0, 1, 1, 1)

        self.label_tool_block_height = QLabel(self.widget_settings)
        self.label_tool_block_height.setObjectName(u"label_tool_block_height")
        self.label_tool_block_height.setAlignment(Qt.AlignCenter)
        self.label_tool_block_height.setMargin(4)

        self.gridLayout_5.addWidget(self.label_tool_block_height, 4, 4, 1, 1)

        self.input_tool_probe_height = QLineEdit(self.widget_settings)
        self.input_tool_probe_height.setObjectName(u"input_tool_probe_height")
        sizePolicy.setHeightForWidth(self.input_tool_probe_height.sizePolicy().hasHeightForWidth())
        self.input_tool_probe_height.setSizePolicy(sizePolicy)
        self.input_tool_probe_height.setMinimumSize(QSize(80, 24))
        self.input_tool_probe_height.setMaximumSize(QSize(80, 24))
        self.input_tool_probe_height.setFont(font2)
        self.input_tool_probe_height.setCursor(QCursor(Qt.IBeamCursor))
        self.input_tool_probe_height.setMaxLength(7)
        self.input_tool_probe_height.setFrame(True)
        self.input_tool_probe_height.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_tool_probe_height, 4, 5, 1, 1)

        self.lab_max_travel = QLabel(self.widget_settings)
        self.lab_max_travel.setObjectName(u"lab_max_travel")
        self.lab_max_travel.setAlignment(Qt.AlignCenter)
        self.lab_max_travel.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_max_travel, 4, 0, 1, 1)

        self.lab_rates = QLabel(self.widget_settings)
        self.lab_rates.setObjectName(u"lab_rates")
        self.lab_rates.setMinimumSize(QSize(0, 24))
        self.lab_rates.setMaximumSize(QSize(16777215, 24))
        self.lab_rates.setFont(font1)
        self.lab_rates.setFrameShape(QFrame.NoFrame)
        self.lab_rates.setFrameShadow(QFrame.Plain)
        self.lab_rates.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.lab_rates, 0, 3, 1, 1)

        self.lab_length = QLabel(self.widget_settings)
        self.lab_length.setObjectName(u"lab_length")
        self.lab_length.setAlignment(Qt.AlignCenter)
        self.lab_length.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_length, 3, 4, 1, 1)

        self.input_xy_clearance = QLineEdit(self.widget_settings)
        self.input_xy_clearance.setObjectName(u"input_xy_clearance")
        sizePolicy.setHeightForWidth(self.input_xy_clearance.sizePolicy().hasHeightForWidth())
        self.input_xy_clearance.setSizePolicy(sizePolicy)
        self.input_xy_clearance.setMinimumSize(QSize(80, 24))
        self.input_xy_clearance.setMaximumSize(QSize(80, 24))
        self.input_xy_clearance.setFont(font2)
        self.input_xy_clearance.setCursor(QCursor(Qt.IBeamCursor))
        self.input_xy_clearance.setMaxLength(7)
        self.input_xy_clearance.setFrame(True)
        self.input_xy_clearance.setCursorPosition(0)
        self.input_xy_clearance.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_xy_clearance, 3, 7, 1, 1)

        self.lab_z_2 = QLabel(self.widget_settings)
        self.lab_z_2.setObjectName(u"lab_z_2")
        self.lab_z_2.setAlignment(Qt.AlignCenter)
        self.lab_z_2.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_z_2, 4, 6, 1, 1)

        self.input_z_clearance = QLineEdit(self.widget_settings)
        self.input_z_clearance.setObjectName(u"input_z_clearance")
        sizePolicy.setHeightForWidth(self.input_z_clearance.sizePolicy().hasHeightForWidth())
        self.input_z_clearance.setSizePolicy(sizePolicy)
        self.input_z_clearance.setMinimumSize(QSize(80, 24))
        self.input_z_clearance.setMaximumSize(QSize(80, 24))
        self.input_z_clearance.setFont(font2)
        self.input_z_clearance.setCursor(QCursor(Qt.IBeamCursor))
        self.input_z_clearance.setMaxLength(7)
        self.input_z_clearance.setFrame(True)
        self.input_z_clearance.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_z_clearance, 4, 7, 1, 1)

        self.lab_clearances = QLabel(self.widget_settings)
        self.lab_clearances.setObjectName(u"lab_clearances")
        self.lab_clearances.setMinimumSize(QSize(0, 24))
        self.lab_clearances.setMaximumSize(QSize(16777215, 24))
        self.lab_clearances.setFont(font1)
        self.lab_clearances.setFrameShape(QFrame.NoFrame)
        self.lab_clearances.setFrameShadow(QFrame.Plain)
        self.lab_clearances.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.lab_clearances, 0, 7, 1, 1)

        self.btn_help = QPushButton(self.widget_settings)
        self.btn_help.setObjectName(u"btn_help")
        sizePolicy1.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy1)
        self.btn_help.setMinimumSize(QSize(0, 24))
        self.btn_help.setMaximumSize(QSize(16777215, 24))

        self.gridLayout_5.addWidget(self.btn_help, 5, 6, 1, 2)

        self.lab_search_vel = QLabel(self.widget_settings)
        self.lab_search_vel.setObjectName(u"lab_search_vel")
        self.lab_search_vel.setAlignment(Qt.AlignCenter)
        self.lab_search_vel.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_search_vel, 4, 2, 1, 1)

        self.lab_probe_rapid = QLabel(self.widget_settings)
        self.lab_probe_rapid.setObjectName(u"lab_probe_rapid")
        self.lab_probe_rapid.setAlignment(Qt.AlignCenter)
        self.lab_probe_rapid.setMargin(4)

        self.gridLayout_5.addWidget(self.lab_probe_rapid, 3, 2, 1, 1)

        self.input_probe_vel = QLineEdit(self.widget_settings)
        self.input_probe_vel.setObjectName(u"input_probe_vel")
        sizePolicy.setHeightForWidth(self.input_probe_vel.sizePolicy().hasHeightForWidth())
        self.input_probe_vel.setSizePolicy(sizePolicy)
        self.input_probe_vel.setMinimumSize(QSize(80, 24))
        self.input_probe_vel.setMaximumSize(QSize(80, 24))
        self.input_probe_vel.setFont(font2)
        self.input_probe_vel.setCursor(QCursor(Qt.IBeamCursor))
        self.input_probe_vel.setMaxLength(7)
        self.input_probe_vel.setFrame(True)
        self.input_probe_vel.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_probe_vel, 5, 3, 1, 1)

        self.input_search_vel = QLineEdit(self.widget_settings)
        self.input_search_vel.setObjectName(u"input_search_vel")
        sizePolicy.setHeightForWidth(self.input_search_vel.sizePolicy().hasHeightForWidth())
        self.input_search_vel.setSizePolicy(sizePolicy)
        self.input_search_vel.setMinimumSize(QSize(80, 24))
        self.input_search_vel.setMaximumSize(QSize(80, 24))
        self.input_search_vel.setFont(font2)
        self.input_search_vel.setCursor(QCursor(Qt.IBeamCursor))
        self.input_search_vel.setMaxLength(7)
        self.input_search_vel.setFrame(True)
        self.input_search_vel.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_search_vel, 4, 3, 1, 1)

        self.input_rapid_vel = QLineEdit(self.widget_settings)
        self.input_rapid_vel.setObjectName(u"input_rapid_vel")
        sizePolicy.setHeightForWidth(self.input_rapid_vel.sizePolicy().hasHeightForWidth())
        self.input_rapid_vel.setSizePolicy(sizePolicy)
        self.input_rapid_vel.setMinimumSize(QSize(80, 24))
        self.input_rapid_vel.setMaximumSize(QSize(80, 24))
        self.input_rapid_vel.setFont(font2)
        self.input_rapid_vel.setCursor(QCursor(Qt.IBeamCursor))
        self.input_rapid_vel.setMaxLength(7)
        self.input_rapid_vel.setFrame(True)
        self.input_rapid_vel.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.input_rapid_vel, 3, 3, 1, 1)


        self.verticalLayout_8.addWidget(self.widget_settings)


        self.horizontalLayout.addWidget(self.widget_probing)


        self.retranslateUi(versaProbe)

        QMetaObject.connectSlotsByName(versaProbe)
    # setupUi

    def retranslateUi(self, versaProbe):
        versaProbe.setWindowTitle(QCoreApplication.translate("versaProbe", u"Form", None))
        self.label_outside_measure.setText(QCoreApplication.translate("versaProbe", u"OUTSIDE", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_xpym.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_xpym.setText("")
        self.pbtn_outside_xpym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_xpym", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_ym.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Y Edge, Negative Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_ym.setText("")
        self.pbtn_outside_ym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_ym", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_xmym.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_xmym.setText("")
        self.pbtn_outside_xmym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_xmym", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_xp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside X Edge, Positive Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_xp.setText("")
        self.pbtn_outside_xp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_xp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_center.setToolTip(QCoreApplication.translate("versaProbe", u"Probe All Outside Edges, Finish In Center", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_center.setText("")
        self.pbtn_outside_center.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_xy_center", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_xm.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside X Edge, Negative Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_xm.setText("")
        self.pbtn_outside_xm.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_xm", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_xpyp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_xpyp.setText("")
        self.pbtn_outside_xpyp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_xpyp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_yp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Y Edge, Positive Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_yp.setText("")
        self.pbtn_outside_yp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_yp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_xmyp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_xmyp.setText("")
        self.pbtn_outside_xmyp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_xmyp", None))
        self.label_adjust.setText(QCoreApplication.translate("versaProbe", u"ADJ OFFSET", None))
        self.label_x.setText(QCoreApplication.translate("versaProbe", u"X", None))
        self.input_adj_x.setText("")
        self.label_y.setText(QCoreApplication.translate("versaProbe", u"Y", None))
        self.input_adj_y.setText("")
        self.label_z.setText(QCoreApplication.translate("versaProbe", u"Z", None))
#if QT_CONFIG(tooltip)
        self.input_adj_z.setToolTip(QCoreApplication.translate("versaProbe", u"Set Z axis to offset value", None))
#endif // QT_CONFIG(tooltip)
        self.input_adj_z.setText("")
        self.label_adjust_angle.setText(QCoreApplication.translate("versaProbe", u"A", None))
#if QT_CONFIG(tooltip)
        self.input_adj_angle.setToolTip(QCoreApplication.translate("versaProbe", u"Set rotation to offset value", None))
#endif // QT_CONFIG(tooltip)
        self.input_adj_angle.setText("")
#if QT_CONFIG(tooltip)
        self.pbtn_set_x.setToolTip(QCoreApplication.translate("versaProbe", u"Set X axis to offset value", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_set_x.setText(QCoreApplication.translate("versaProbe", u"SET\n"
"X", None))
#if QT_CONFIG(tooltip)
        self.pbtn_set_y.setToolTip(QCoreApplication.translate("versaProbe", u"Set Y axis to offset value", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_set_y.setText(QCoreApplication.translate("versaProbe", u"SET\n"
"Y", None))
#if QT_CONFIG(tooltip)
        self.pbtn_set_z.setToolTip(QCoreApplication.translate("versaProbe", u"Set Z axis to offset value", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_set_z.setText(QCoreApplication.translate("versaProbe", u"SET\n"
"Z", None))
        self.label_inside_measure.setText(QCoreApplication.translate("versaProbe", u"INSIDE", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xmyp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xmyp.setText("")
        self.pbtn_inside_xmyp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_inside_xmyp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_yp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Inside Y Edge, Positive Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_yp.setText("")
        self.pbtn_inside_yp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_yp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xpyp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xpyp.setText("")
        self.pbtn_inside_xpyp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_inside_xpyp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xm.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Inside X Edge, Negative Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xm.setText("")
        self.pbtn_inside_xm.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_xm", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xy_hole.setToolTip(QCoreApplication.translate("versaProbe", u"Probe All Inside Edges, Finish In Center", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xy_hole.setText("")
        self.pbtn_inside_xy_hole.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_xy_hole", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xp.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Inside Y Edge, Negative Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xp.setText("")
        self.pbtn_inside_xp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_xp", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xmym.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xmym.setText("")
        self.pbtn_inside_xmym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_inside_xmym", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_ym.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Inside Y Edge, Negative Direction, Finsh At Edge", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_ym.setText("")
        self.pbtn_inside_ym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_ym", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_xpym.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Outside Edges, Finish At Corner", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_xpym.setText("")
        self.pbtn_inside_xpym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_inside_xpym", None))
#if QT_CONFIG(tooltip)
        self.allow_auto_zero.setToolTip(QCoreApplication.translate("versaProbe", u"Enable auto zero of probed location", None))
#endif // QT_CONFIG(tooltip)
        self.allow_auto_zero.setText(QCoreApplication.translate("versaProbe", u"AUTO\n"
"ZERO", None))
#if QT_CONFIG(tooltip)
        self.allow_auto_skew.setToolTip(QCoreApplication.translate("versaProbe", u"Enable auto rotation to probed skew measurement", None))
#endif // QT_CONFIG(tooltip)
        self.allow_auto_skew.setText(QCoreApplication.translate("versaProbe", u"AUTO\n"
"SKEW", None))
#if QT_CONFIG(shortcut)
        self.allow_auto_skew.setShortcut("")
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pbtn_set_angle.setToolTip(QCoreApplication.translate("versaProbe", u"Set axis rotation angle", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_set_angle.setText(QCoreApplication.translate("versaProbe", u"SET\n"
"ANGLE", None))
#if QT_CONFIG(tooltip)
        self.pbtn_use_tool_measurement.setToolTip(QCoreApplication.translate("versaProbe", u"This button not implemented", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_use_tool_measurement.setText(QCoreApplication.translate("versaProbe", u"MEASURE\n"
"TOOL", None))
        self.label_skewed_label.setText(QCoreApplication.translate("versaProbe", u"SKEW", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_length_x.setToolTip(QCoreApplication.translate("versaProbe", u"Measure Outside Length of X, Finish in Center", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_length_x.setText("")
        self.pbtn_outside_length_x.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_length_x", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_length_x.setToolTip(QCoreApplication.translate("versaProbe", u"Measure Inside Length of X, Finish in Center", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_length_x.setText("")
        self.pbtn_inside_length_x.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_inside_length_x", None))
        self.pbtn_skew_xp.setText("")
        self.pbtn_skew_xp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_angle_xp", None))
        self.pbtn_skew_yp.setText("")
        self.pbtn_skew_yp.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_angle_yp", None))
        self.pbtn_skew_ym.setText("")
        self.pbtn_skew_ym.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_angle_ym", None))
        self.pbtn_skew_xm.setText("")
        self.pbtn_skew_xm.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_angle_xm", None))
#if QT_CONFIG(tooltip)
        self.pbtn_measure_diam.setToolTip(QCoreApplication.translate("versaProbe", u"This button not implemented", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_measure_diam.setText("")
        self.pbtn_measure_diam.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_help", None))
#if QT_CONFIG(tooltip)
        self.pbtn_inside_length_y.setToolTip(QCoreApplication.translate("versaProbe", u"Measure Inside Length of Y, Finish in Center", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_inside_length_y.setText("")
        self.pbtn_inside_length_y.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_inside_length_y", None))
#if QT_CONFIG(tooltip)
        self.pbtn_down.setToolTip(QCoreApplication.translate("versaProbe", u"Probe Z down", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_down.setText("")
        self.pbtn_down.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_down", None))
#if QT_CONFIG(tooltip)
        self.pbtn_outside_length_y.setToolTip(QCoreApplication.translate("versaProbe", u"Measure Outside Length of Y, Finish in Center", None))
#endif // QT_CONFIG(tooltip)
        self.pbtn_outside_length_y.setText("")
        self.pbtn_outside_length_y.setProperty("probe", QCoreApplication.translate("versaProbe", u"probe_outside_length_y", None))
        self.lbl_lengths.setText(QCoreApplication.translate("versaProbe", u"LENGTHS", None))
        self.lbl_results.setText(QCoreApplication.translate("versaProbe", u"RESULTS", None))
        self.lab_xn.setText(QCoreApplication.translate("versaProbe", u"X NEG", None))
        self.status_xm.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_xc.setText(QCoreApplication.translate("versaProbe", u"X CTR", None))
        self.status_xc.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_xp.setText(QCoreApplication.translate("versaProbe", u"X POS", None))
        self.status_xp.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_lx.setText(QCoreApplication.translate("versaProbe", u"LEN X", None))
        self.status_lx.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_yn.setText(QCoreApplication.translate("versaProbe", u"Y NEG", None))
        self.status_ym.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_yc.setText(QCoreApplication.translate("versaProbe", u"Y CTR", None))
        self.status_yc.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_yp.setText(QCoreApplication.translate("versaProbe", u"Y POS", None))
        self.status_yp.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_ly.setText(QCoreApplication.translate("versaProbe", u"LEN Y", None))
        self.status_ly.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_z.setText(QCoreApplication.translate("versaProbe", u"Z", None))
        self.status_z.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_diam.setText(QCoreApplication.translate("versaProbe", u"DIAM", None))
        self.status_d.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_ang.setText(QCoreApplication.translate("versaProbe", u"ANGLE", None))
        self.status_a.setPlaceholderText(QCoreApplication.translate("versaProbe", u"0", None))
        self.lab_probe_vel.setText(QCoreApplication.translate("versaProbe", u"PROBE", None))
#if QT_CONFIG(tooltip)
        self.input_side_edge_length.setToolTip(QCoreApplication.translate("versaProbe", u"Edge length", None))
#endif // QT_CONFIG(tooltip)
        self.input_side_edge_length.setText("")
        self.lab_latch_rtrn_dist.setText(QCoreApplication.translate("versaProbe", u"LATCH RTN", None))
        self.lab_ball_diam.setText(QCoreApplication.translate("versaProbe", u"DIAMETER", None))
#if QT_CONFIG(tooltip)
        self.input_probe_diam.setToolTip(QCoreApplication.translate("versaProbe", u"Probe diameter", None))
#endif // QT_CONFIG(tooltip)
        self.input_probe_diam.setInputMask("")
        self.input_probe_diam.setText("")
#if QT_CONFIG(tooltip)
        self.input_latch_return_dist.setToolTip(QCoreApplication.translate("versaProbe", u"Latch return distance", None))
#endif // QT_CONFIG(tooltip)
        self.input_latch_return_dist.setText("")
        self.lab_xy.setText(QCoreApplication.translate("versaProbe", u"XY", None))
        self.label_tool_block_height_2.setText(QCoreApplication.translate("versaProbe", u"BLOCK HT", None))
#if QT_CONFIG(tooltip)
        self.input_tool_block_height.setToolTip(QCoreApplication.translate("versaProbe", u"Tool block height", None))
#endif // QT_CONFIG(tooltip)
        self.input_tool_block_height.setText("")
        self.lab_side_edge.setText(QCoreApplication.translate("versaProbe", u"SIDE/EDGE", None))
#if QT_CONFIG(tooltip)
        self.input_max_travel.setToolTip(QCoreApplication.translate("versaProbe", u"Maximum travel during search", None))
#endif // QT_CONFIG(tooltip)
        self.input_max_travel.setText("")
        self.lab_probe.setText(QCoreApplication.translate("versaProbe", u"PROBE", None))
        self.label_tool_block_height.setText(QCoreApplication.translate("versaProbe", u"PROBE HT", None))
#if QT_CONFIG(tooltip)
        self.input_tool_probe_height.setToolTip(QCoreApplication.translate("versaProbe", u"Tool probe height", None))
#endif // QT_CONFIG(tooltip)
        self.input_tool_probe_height.setText("")
        self.lab_max_travel.setText(QCoreApplication.translate("versaProbe", u"TRAVEL", None))
        self.lab_rates.setText(QCoreApplication.translate("versaProbe", u"RATES", None))
        self.lab_length.setText(QCoreApplication.translate("versaProbe", u"LENGTH", None))
#if QT_CONFIG(tooltip)
        self.input_xy_clearance.setToolTip(QCoreApplication.translate("versaProbe", u"Distance to move before starting search", None))
#endif // QT_CONFIG(tooltip)
        self.input_xy_clearance.setText("")
        self.lab_z_2.setText(QCoreApplication.translate("versaProbe", u"Z ", None))
#if QT_CONFIG(tooltip)
        self.input_z_clearance.setToolTip(QCoreApplication.translate("versaProbe", u"Distance to move Z up or down during search", None))
#endif // QT_CONFIG(tooltip)
        self.input_z_clearance.setText("")
        self.lab_clearances.setText(QCoreApplication.translate("versaProbe", u"CLEARANCE", None))
        self.btn_help.setText(QCoreApplication.translate("versaProbe", u"VersaProbe Help", None))
        self.lab_search_vel.setText(QCoreApplication.translate("versaProbe", u"SEARCH", None))
        self.lab_probe_rapid.setText(QCoreApplication.translate("versaProbe", u"RAPID", None))
#if QT_CONFIG(tooltip)
        self.input_probe_vel.setToolTip(QCoreApplication.translate("versaProbe", u"Probe velocity", None))
#endif // QT_CONFIG(tooltip)
        self.input_probe_vel.setText("")
#if QT_CONFIG(tooltip)
        self.input_search_vel.setToolTip(QCoreApplication.translate("versaProbe", u"Search velocity", None))
#endif // QT_CONFIG(tooltip)
        self.input_search_vel.setText("")
#if QT_CONFIG(tooltip)
        self.input_rapid_vel.setToolTip(QCoreApplication.translate("versaProbe", u"Probe rapid velocity", None))
#endif // QT_CONFIG(tooltip)
        self.input_rapid_vel.setText("")
    # retranslateUi

