#!/bin/bash
#                                                   -*-shell-script-*-
# Machinekit has own tests for hm2 drivers with incompatible headers

if test "$HAL_PKG" = machinekit-hal; then
    exit 1
fi
